from ..base import AgentEvent as AgentEvent, try_json as try_json

def parse_events(stdout: str) -> list[AgentEvent]: ...

class StreamParser:
    session_id: str | None
    saw_delta: bool
    result: dict | None
    def __init__(self) -> None: ...
    def feed(self, line: str) -> list[AgentEvent]: ...
    def finish(self) -> list[AgentEvent]: ...
