from . import transcript as transcript
from .. import binaries as binaries
from ..base import ASK_SERVER_NAME as ASK_SERVER_NAME, AgentEvent as AgentEvent, TurnOptions as TurnOptions, add_flag as add_flag, try_json as try_json
from ..caps import Capabilities as Capabilities
from ..cli import CliBackend as CliBackend
from .claudeparse import StreamParser as StreamParser, parse_events as parse_events

class ClaudeBackend(CliBackend):
    name: str
    def build_args(self, prompt: str, session_id: str | None, options: TurnOptions) -> list[str]: ...
    def capabilities(self) -> Capabilities: ...
    def efforts(self, model: str | None = None) -> list[str]: ...
    def last_response(self, session_id: str, cwd: str) -> str: ...
    def occupancy(self, session_id: str, cwd: str) -> int | None: ...
    def env(self, options: TurnOptions) -> dict | None: ...
    def supports_ask(self, options: TurnOptions) -> bool: ...
    def stream_parser(self) -> StreamParser: ...
    def parse(self, stdout: str) -> list[AgentEvent]: ...
    def list_sessions(self, cwd: str) -> list[dict]: ...
