def session_rows(cwd: str) -> list[tuple]: ...
def recent_models(since_ms: float) -> list[tuple[str, int, float]]: ...
def model_of(model_json: str | None) -> str | None: ...
def context_used(data: dict) -> int | None: ...
def last_model(session_id: str) -> str | None: ...
def last_turn(session_id: str) -> tuple[str, int | None]: ...
