from . import catalog as catalog, ocstore as ocstore
from .. import binaries as binaries
from ..base import ASK_SERVER_NAME as ASK_SERVER_NAME, AgentEvent as AgentEvent, TurnOptions as TurnOptions, add_flag as add_flag, try_json as try_json
from ..caps import Capabilities as Capabilities
from ..cli import CliBackend as CliBackend

def parse_events(stdout: str) -> list[AgentEvent]: ...

class LineStream:
    def feed(self, line: str) -> list[AgentEvent]: ...
    def finish(self) -> list[AgentEvent]: ...

class OpencodeBackend(CliBackend):
    name: str
    def build_args(self, prompt: str, session_id: str | None, options: TurnOptions) -> list[str]: ...
    def env(self, options: TurnOptions) -> dict | None: ...
    def supports_ask(self, options: TurnOptions) -> bool: ...
    def parse(self, stdout: str) -> list[AgentEvent]: ...
    def stream_parser(self) -> LineStream: ...
    def capabilities(self) -> Capabilities: ...
    def efforts(self, model: str | None = None) -> list[str]: ...
    def list_sessions(self, cwd: str) -> list[dict]: ...
    def last_response(self, session_id: str, cwd: str) -> str: ...
    def occupancy(self, session_id: str, cwd: str) -> int | None: ...
    def model_used(self, session_id: str, cwd: str) -> str | None: ...
    def session_detail(self, session_id: str, cwd: str) -> dict: ...
