import pathlib
from ..base import try_json as try_json

def tail_lines(path: pathlib.Path, kb: int = 64) -> list[str]: ...
def latest_ai_title(lines: list[str]) -> str: ...
def last_response_text(lines: list[str]) -> str: ...
def last_context_used(lines: list[str]) -> int | None: ...
def last_model(lines: list[str]) -> str | None: ...
