from conftest import WORKSPACE_ROOT as WORKSPACE_ROOT

def test_load_and_save_config(tmp_path) -> None: ...
def test_load_and_save_cache(tmp_path) -> None: ...
def test_debounce_is_active_within_ttl() -> None: ...
def test_sync_directory_returns_error_without_config(tmp_path) -> None: ...
def test_sync_directory_skips_when_debounce_active(tmp_path, monkeypatch) -> None: ...
def test_sync_directory_downloads_changed_items_and_updates_cache(tmp_path, monkeypatch): ...
def test_sync_file_item_routes_slide_previews(tmp_path, monkeypatch): ...
