import subprocess
from _typeshed import Incomplete
from pathlib import Path
from typing import Any

PATH_KEYS: Incomplete
CONTENT_KEYS: Incomplete
OLD_KEYS: Incomplete
NEW_KEYS: Incomplete
COMMAND_KEYS: Incomplete

def load_input() -> dict[str, Any]: ...
def session_id() -> str: ...
def normalize_path(workspace_root: Path, raw: Any) -> str | None: ...
def collect_paths(workspace_root: Path, value: Any) -> list[str]: ...
def first_string(value: Any, keys: tuple[str, ...]) -> str: ...
def build_payload(file_path: str, tool_input: dict[str, Any]) -> dict[str, Any]: ...
def run_script(script: Path, payload: dict[str, Any], tool_name: str, workspace_root: Path, via_env: bool = False) -> subprocess.CompletedProcess[str]: ...
def forward_block(result: subprocess.CompletedProcess[str]) -> int: ...
