from pathlib import Path

def load_input() -> dict: ...
def read_workspace_excerpt(workspace_root: Path, max_lines: int = 120) -> str: ...
def load_caveman_context() -> str: ...
def main() -> int: ...
