def state_file(session_id: str) -> str: ...
def announced(session_id: str) -> int: ...
def mark(session_id: str, threshold: int) -> None: ...
def message(ctx: int, crossed: int, loud: int) -> str: ...
def main() -> None: ...
