from _typeshed import Incomplete

RUN: Incomplete
TIMEOUT: int

def last_sent(session_id: str) -> float: ...
def mark(session_id: str) -> None: ...
def muted(session_id: str, cooldown: int) -> bool: ...
def line(raw: dict, cwd: str) -> str: ...
def tell(text: str) -> None: ...
def main() -> None: ...
