CELLS: int

def remembered(session_id: str) -> tuple[int, int]: ...
def remember(session_id: str, ctx: int, step: int) -> None: ...
def bar(ctx: int, warn: int, loud: int) -> str: ...
def line(ctx: int, step: int, warn: int, loud: int) -> str: ...
def main() -> None: ...
