from _typeshed import Incomplete
from pathlib import Path as Path

SHIM: Incomplete

def test_feature_toggle_disabled(monkeypatch) -> None: ...
def test_pre_tool_run_command_allowed() -> None: ...
def test_pre_tool_run_command_blocked_context_gate() -> None: ...
def test_pre_tool_run_command_warns_heredoc() -> None: ...
def test_pre_tool_view_file_unseen_subtree_blocked() -> None: ...
def test_pre_tool_grep_search_unseen_subtree_blocked() -> None: ...
def test_pre_tool_write_to_file_size_gate_blocked() -> None: ...
def test_post_tool_view_file_records_tracker() -> None: ...
def test_pre_invocation_returns_dict() -> None: ...
