from _typeshed import Incomplete

RATCHET: Incomplete
BROKEN_JSON: str
FIXED_JSON: str
BROKEN_SH: str
BOUNDARY_JS: str

def test_the_registration_that_broke_it_is_caught(tmp_path) -> None: ...
def test_the_shell_arm_still_catches_what_it_always_did(tmp_path) -> None: ...
def test_asking_the_boundary_is_not_a_finding(tmp_path) -> None: ...
def test_every_shim_reaches_the_trackers_through_the_table() -> None: ...
