from _typeshed import Incomplete

CORE: Incomplete
HOOKS: Incomplete
SHIMS: Incomplete
REGISTRATIONS: Incomplete

def test_every_registration_spawns_its_shim_through_the_launcher() -> None: ...
def test_every_shim_names_at_least_one_canonical_script() -> None: ...
def test_every_shim_reaches_the_dispatcher() -> None: ...
def test_opencode_spawns_only_scripts_that_exist() -> None: ...
def test_copilot_spawns_only_scripts_that_exist() -> None: ...
def test_zcode_spawns_only_scripts_that_exist() -> None: ...
def test_claude_spawns_only_scripts_that_exist() -> None: ...
def test_antigravity_spawns_only_scripts_that_exist() -> None: ...
def test_opencode_shim_resolves_the_interpreter_through_the_boundary() -> None: ...
def test_the_launcher_every_shim_goes_through_is_there() -> None: ...
