from _typeshed import Incomplete

HARNESS_FILE: Incomplete

def test_the_declaration_itself_is_tracked() -> None: ...
def test_no_literal_mirror_path_survives_in_the_source() -> None: ...
def test_every_declared_mirror_has_its_gitignore_line() -> None: ...
def test_no_gitignore_mirror_names_an_undeclared_harness() -> None: ...
