def test_opencode_has_text_and_result() -> None: ...
def test_opencode_text_and_session() -> None: ...
def test_opencode_contract() -> None: ...
def test_list_sessions_filters_dir_and_toplevel(tmp_path, monkeypatch): ...
def test_list_sessions_no_db_is_empty(tmp_path, monkeypatch): ...
