class _FakeProc:
    returncode: int
    async def communicate(self): ...

def test_pwd_names_the_directory_the_turn_was_given(monkeypatch) -> None: ...
def test_both_backends_are_pinned_the_same_way(monkeypatch) -> None: ...
def test_a_backend_knob_cannot_take_pwd_over(monkeypatch) -> None: ...
def test_the_streaming_path_pins_it_too(monkeypatch) -> None: ...
