def test_claude_has_text_and_result() -> None: ...
def test_claude_text_and_session() -> None: ...
def test_claude_contract() -> None: ...
def test_resume_is_single_lineage_no_fork() -> None: ...
def test_build_args_build_mode_keeps_bypass() -> None: ...
def test_build_args_plan_mode_sets_permission_plan() -> None: ...
def test_build_args_new_session_sets_name() -> None: ...
def test_build_args_resume_omits_name() -> None: ...
def test_build_args_new_without_title_omits_name() -> None: ...
def test_list_sessions_reads_store(tmp_path, monkeypatch): ...
def test_list_sessions_prefers_ai_title_over_prompt(tmp_path, monkeypatch): ...
def test_list_sessions_enriches_preview_and_model(tmp_path, monkeypatch): ...
def test_list_sessions_missing_dir_is_empty(tmp_path, monkeypatch): ...
def test_the_result_object_gives_the_window_but_never_the_occupancy() -> None: ...
def test_env_sets_entrypoint_so_sessions_are_natively_listed() -> None: ...
