def test_claude_fixture_consolidates_to_result() -> None: ...
def test_opencode_fixture_consolidates_to_result() -> None: ...
def test_error_event_raises_dispatch_error() -> None: ...
def test_missing_result_event_raises_dispatch_error() -> None: ...
def test_model_flows_from_result_event() -> None: ...
