def test_an_error_line_becomes_an_error_event_carrying_the_real_reason() -> None: ...
def test_the_error_event_keeps_the_session_it_belongs_to() -> None: ...
def test_the_nested_message_wins_over_the_useless_outer_name() -> None: ...
def test_a_bare_name_is_used_when_there_is_no_nested_message() -> None: ...
def test_an_unrecognized_error_shape_still_names_itself() -> None: ...
def test_the_user_sees_the_reason_not_the_contract_complaint() -> None: ...
def test_zero_recognized_events_on_a_clean_exit_still_reports_something(): ...
def test_the_net_falls_back_to_stderr_when_the_cli_streamed_nothing(): ...
def test_a_parser_that_did_recognize_events_is_left_alone(): ...
