def test_claude_maps_model_and_effort() -> None: ...
def test_claude_omits_unset_knobs() -> None: ...
def test_claude_declares_aliases_as_its_whole_catalogue() -> None: ...
def test_claude_effort_ladder_is_model_independent() -> None: ...
def test_opencode_maps_model_effort_and_plan_agent() -> None: ...
def test_opencode_titles_a_new_session_instead_of_resuming() -> None: ...
def test_opencode_effort_is_per_model(monkeypatch): ...
def test_every_registered_backend_declares_its_capabilities(monkeypatch) -> None: ...
