from _typeshed import Incomplete

HERE: Incomplete
CORE: Incomplete
REGISTRY_FILE: Incomplete
PROFILE_FILE: Incomplete
LOCAL_PROFILE_FILE: Incomplete
GROUPS: Incomplete
RUNS: Incomplete
ENFORCEMENT: Incomplete
SCOPES: Incomplete
OFF_ENV: str

def load_registry() -> list: ...
def names() -> set: ...
def load_profile() -> dict: ...
def is_enabled(name: str) -> bool: ...
def setting(key: str, default: str = '') -> str: ...
def groups(row: dict) -> list: ...
def is_wired(row: dict) -> bool: ...
def wired_paths(row: dict) -> list: ...
def findings() -> list: ...
def disabled() -> list: ...
def main() -> int: ...
