from _typeshed import Incomplete
from pathlib import Path

HERE: Incomplete
LIMITS_FILE: Incomplete
VENDORED_FILE: Incomplete
GENERATED_FILE: Incomplete
EXTENSIONLESS_FILE: Incomplete
DESCRIBED_FILE: Incomplete
CODE_EXTS: Incomplete
GENERATED: Incomplete
FACADES: Incomplete
EXAMPLE_COMMENT: Incomplete

def is_tool_entrypoint(path: Path) -> bool: ...
def is_code_file(path: Path) -> bool: ...
def load_limits() -> dict: ...
def allowed_extensionless() -> set: ...
def is_vendored(path: Path, root: Path) -> bool: ...
def is_generated_artifact(path: Path, root: Path) -> bool: ...
def described() -> dict: ...
def is_authored(path: Path, root: Path) -> bool: ...

BLOCK_OPEN: Incomplete
BLOCK_CLOSE: Incomplete

def generated_spans(text: str) -> list: ...
def is_generated_line(text: str, number: int) -> bool: ...
def is_authored_prose(path: Path, root: Path) -> bool: ...
