from pathlib import Path
from typing import Any

def parse_stdin() -> tuple[dict[str, Any], str, dict[str, Any], str, str]: ...
def capability(tool: str, tool_input: dict[str, Any]) -> str: ...
def is_subagent(raw: dict[str, Any]) -> bool: ...
def normalise(raw: str) -> str: ...
def store(session_id: str, kind: str) -> Path: ...
def load_seen(session_id: str) -> set[str]: ...
def mark_seen(session_id: str, path: str) -> None: ...
def load_iface_seen(session_id: str) -> set[str]: ...
def mark_iface_seen(session_id: str, path: str) -> None: ...
def load_facades(session_id: str) -> set[str]: ...
def mark_facade(session_id: str, path: str) -> None: ...
def announced(session_id: str, kind: str, key: str) -> bool: ...
