from _typeshed import Incomplete
from pathlib import Path

WORKSPACE_ROOT: Incomplete
POSIX_VENV_BIN: str
WINDOWS_VENV_BIN: str
AUTHORING_ROOT: str

def venv_script(name: str) -> Path: ...
def interpreter() -> str: ...
def session_state(name: str) -> Path: ...
def install_command(directory, name: str, source: str) -> None: ...
def package_install(name: str) -> list: ...
def posix(path) -> str: ...
def rel(path, root=...) -> str: ...
def is_owner_only(path) -> bool: ...
def secure_dir(path) -> None: ...
def secure_file(path) -> None: ...
