from _typeshed import Incomplete
from pathlib import Path

HERE: Incomplete
CORE: Incomplete
STORE: str

def path() -> Path: ...
def enabled() -> bool: ...
def record(name: str, event: str) -> None: ...
def tally(store: Path = None) -> dict: ...
def started() -> str: ...
