from _typeshed import Incomplete
from typing import Any

HOOKS: Incomplete

def run_gate(script: str, payload: dict[str, Any], tool: str, extra_args: list[str] | None = None) -> tuple[int, str]: ...
def said(msg: str) -> str: ...
def pre_tool(call: dict[str, Any], sid: str) -> dict[str, Any]: ...
def post_tool(call: dict[str, Any], sid: str) -> dict[str, Any]: ...
def pre_invocation(data: dict[str, Any]) -> dict[str, Any]: ...
def main() -> int: ...
