from dataclasses import dataclass, field
from pathlib import Path

class Blocked(Exception): ...

def git(*args, cwd=None) -> str: ...
def spawn(commit, relative, *args, stdin=None): ...

@dataclass
class Commit:
    root: Path
    toplevel: Path
    staged: list = field(default_factory=list)
    deleted: list = field(default_factory=list)
    @property
    def is_workspace(self) -> bool: ...
    @property
    def code_files(self) -> list: ...
    def matching(self, *suffixes, exclude=()) -> list: ...
    def existing(self, paths) -> list: ...

def collect() -> Commit: ...
def stages() -> list: ...
def main() -> int: ...
