from _typeshed import Incomplete
from pathlib import Path

HOOKS: Incomplete
ROOT_BLOCK: str

def area_of(path: str) -> str: ...
def trigger_of(area: str) -> tuple: ...
def lifecycle(rows: list) -> tuple: ...
def features() -> list: ...
def matrix(rows: list) -> tuple: ...
def fan_in(rows: list, by: str = 'path') -> tuple: ...
def unwired(rows: list) -> list: ...
def containment(root: Path = ...) -> tuple: ...
def mass(root: Path = ..., depth: int = 2) -> list: ...
def scope(root: Path = ...) -> dict: ...
