# The canonical data behind ARCHITECTURE.html: what the workspace declares, what contains what,
# and how much of it there is.
#
# Every fact here is read from a DECLARED or GENERATED file — core/features.txt and the auto-synced
# routing blocks — never from prose and never from a guess. That is what makes the picture no more
# wrong than its sources: a wrong edge is a real defect in the source, made visible instead of
# staying hidden. The firing moment was the one exception until 2026-08-18, guessed from directory
# convention and labelled `inferred` everywhere; core/hooks/trigger/trigger_law.py reads it out
# of the registrations instead, so the exception is gone and this module has none.
import sys
from pathlib import Path

HOOKS = Path(__file__).resolve().parents[3] / 'hooks'
for _dir in (HOOKS, HOOKS / 'routing', HOOKS / 'entropy', HOOKS / 'trigger'):
    sys.path.insert(0, str(_dir))

import feature_law  # noqa: E402
import trigger_law  # noqa: E402
from context_synchronizer import RE as ROUTING_END  # noqa: E402
from context_synchronizer import RS as ROUTING_START  # noqa: E402
from entropy_corpus import nested_repos, tracked_files  # noqa: E402
from platform_law import rel as _rel  # noqa: E402
from schema_law import WORKSPACE_ROOT  # noqa: E402
from workspace_scanner import parse_preserved_subs  # noqa: E402

# The workspace root's routing block lives in AGENTS.md — every other directory keeps its own in
# CONTEXT.md. Missing that one would drop the whole first level of the tree.
ROOT_BLOCK = 'AGENTS.md'

def area_of(path: str) -> str:
    """The directory a wired path lands in — the matrix's column.

    Two features wired into the same directory share a column on purpose: the column is the
    enforcement SITE, not the file, and reading which sites carry which features is the whole
    question the matrix answers.
    """
    path = path.strip()
    if not path or path == '-':
        return ''
    return str(Path(path).parent)


def trigger_of(area: str) -> tuple:
    """(when it fires, declared?) for an enforcement SITE: the moments of the files wired into it.

    Was a 13-entry dict keyed on directory convention, which every consumer had to label
    `inferred` and which put the norms at "on save" because they are generated by a file that runs
    then. The honest answer for a site nothing registers is now `not declared` — a gap the page can
    count, rather than a guess it has to apologise for.
    """
    moments = trigger_law.ordered([moment for path, moments in trigger_law.sites().items()
                                   if str(Path(path).parent) == area for moment in moments])
    return ' · '.join(moments) or 'not declared', bool(moments)


def lifecycle(rows: list) -> tuple:
    """([(moment, [features])], on-demand features, features nothing places) — the session in order.

    Every declared moment gets a band even when it holds nothing, for the same reason `by_layer`
    keeps an empty layer: a moment with no feature on it is a gap in the chain, and a drawing built
    only from what exists can never show what does not.
    """
    bands: dict = {moment: [] for moment in trigger_law.MOMENTS}
    on_demand, unplaced = [], []
    for row in rows:
        moments, source = trigger_law.moments_of(row)
        if source == 'on-demand':
            on_demand.append(row)
        elif not moments:
            unplaced.append(row)
        for moment in moments:
            bands[moment].append(row)
    return [(moment, bands[moment]) for moment in trigger_law.MOMENTS], on_demand, unplaced


def features() -> list:
    """Every declared feature, in registry order, with its wiring collapsed to enforcement sites."""
    rows = []
    for row in feature_law.load_registry():
        areas = sorted({a for a in (area_of(p) for p in feature_law.wired_paths(row)) if a})
        rows.append({**row, 'areas': areas, 'wired_paths': feature_law.wired_paths(row)})
    return rows


def matrix(rows: list) -> tuple:
    """(row labels, column labels, cells) for the enforcement matrix.

    Rows are features, columns are enforcement sites, and a cell holds the enforcement strength
    the registry declares. Both axes come from core/features.txt alone, so the matrix cannot say
    anything the registry does not — an empty column means nothing is wired there, which is a
    finding about the workspace rather than about the drawing.
    """
    cells = {}
    # Grouped, then alphabetical. Registry order is declaration order and interleaves the layers,
    # which printed the same group heading five times — a table that makes a reader re-find the
    # section they are already in.
    rows = sorted(rows, key=lambda r: (r['group'], r['name']))
    for row in rows:
        for area in row['areas']:
            cells[(row['name'], area)] = row['enforcement']
    columns = sorted({area for row in rows for area in row['areas']})
    return rows, columns, cells


def fan_in(rows: list, by: str = 'path') -> tuple:
    """([(point, [name]) busiest first], [name nothing switches]) — where the switches concentrate.

    The matrix draws this same relation as a grid and spends most of its cells on the points that
    carry exactly one feature — 43 of the 47. Read as fan-in instead, the shape arrives at once:
    two files switch off a third of the workspace. `by` picks the grain — 'path' is the file that
    reads the law, 'area' is its directory, the two the matrix and `area_of` already use. Ties
    break on the point's name, so the drawing is byte-identical run to run and --check still means
    something.
    """
    points: dict = {}
    for row in rows:
        for key in (row['areas'] if by == 'area' else row['wired_paths']):
            points.setdefault(key, []).append(row['name'])
    ranked = sorted(points.items(), key=lambda kv: (-len(kv[1]), kv[0]))
    return [(point, sorted(names)) for point, names in ranked], [r['name'] for r in unwired(rows)]


def unwired(rows: list) -> list:
    """Features no file switches off. `core/tools/wos/features --findings` counts these; the
    picture shows them, because a feature entangled with this repo is invisible in a diagram
    of wiring and that invisibility is the finding."""
    return [row for row in rows if not row['areas']]


def _routing_inner(text: str):
    """The rows between the routing sentinels, or None when the block cannot be sliced."""
    if ROUTING_START not in text or ROUTING_END not in text:
        return None
    return text.split(ROUTING_START, 1)[1].split(ROUTING_END, 1)[0]


def _routing_files(root: Path) -> list:
    """Every file carrying a routing block: the root's AGENTS.md, then every tracked CONTEXT.md.
    git is the inventory, so an untracked scratch copy never enters the picture."""
    files = [root / ROOT_BLOCK] if (root / ROOT_BLOCK).exists() else []
    return files + sorted(p for p in tracked_files(root) if p.name == 'CONTEXT.md')


def _rel_dir(path: Path, root: Path) -> str:
    rel = _rel(path.parent, root)
    return '' if rel == '.' else rel


def containment(root: Path = WORKSPACE_ROOT) -> tuple:
    """(nodes, edges, coverage) — the routing chain, parent directory to child directory.

    Total and fail-loud: a routing block that cannot be sliced is COUNTED and NAMED in `coverage`,
    never skipped. A picture that silently drops a subtree is exactly the rot the routing tables
    exist to prevent, so the generator refuses to produce one quietly.
    """
    nodes, edges, unparsed = {'': 0}, [], []
    files = _routing_files(root)
    for path in files:
        inner = _routing_inner(path.read_text(encoding='utf-8', errors='replace'))
        if inner is None:
            unparsed.append(_rel(path, root))
            continue
        parent = _rel_dir(path, root)
        for name in sorted(parse_preserved_subs(inner)):
            child = f'{parent}/{name}' if parent else name
            nodes.setdefault(child, child.count('/') + 1)
            edges.append((parent, child))
    for parent, _child in edges:
        nodes.setdefault(parent, parent.count('/') + 1 if parent else 0)
    coverage = {'total': len(files), 'parsed': len(files) - len(unparsed), 'unparsed': unparsed}
    return nodes, edges, coverage


def mass(root: Path = WORKSPACE_ROOT, depth: int = 2) -> list:
    """Tracked-file mass per directory, folded to `depth` levels: [(dir, files, bytes)].

    git ls-files is the inventory rather than a walk, which is what keeps .venv, Downloads/ and
    the trash out of a picture of the workspace — three directories that dwarf everything real.
    """
    totals: dict = {}
    for path in tracked_files(root):
        parts = path.relative_to(root).parts[:-1]
        key = '/'.join(parts[:depth]) if parts else '(root)'
        files, size = totals.get(key, (0, 0))
        try:
            totals[key] = (files + 1, size + path.stat().st_size)
        except OSError:
            totals[key] = (files + 1, size)
    return sorted(((k, v[0], v[1]) for k, v in totals.items()), key=lambda r: -r[2])


def scope(root: Path = WORKSPACE_ROOT) -> dict:
    """What the document covers. Repos nested inside the workspace are COUNTED and drawn as
    directories, never walked into: each is its own repository with its own history, and folding
    one into this picture would claim an authority over it that this repo does not have."""
    return {'nested': len(nested_repos(root))}
