from pathlib import Path

def harness_owned(rel: str) -> bool: ...
def orphans(root: Path = ...) -> list: ...
def by_layer(rows: list, runs: str = '') -> list: ...
def findings(rows: list, coverage: dict, root: Path = ...) -> list: ...
def detail(rows: list, root: Path = ...) -> dict: ...
