import asyncio
from . import askshape as askshape
from .. import phrases as phrases, reply as reply
from ..session import msgmap as msgmap
from .askshape import ENDED_TEXT as ENDED_TEXT, EXPIRED_TEXT as EXPIRED_TEXT, NO_ANSWER_NOTE as NO_ANSWER_NOTE, TAP as TAP, TIMEOUT_TEXT as TIMEOUT_TEXT
from _typeshed import Incomplete
from dataclasses import dataclass, field

WAIT_SECONDS: Incomplete

@dataclass
class _Question:
    token: str
    future: asyncio.Future
    options: list[str] = field(default_factory=list)
    bubble: object | None = ...
    text: str = ...

def new_token() -> str: ...
def register(token: str, msg, live=None) -> None: ...
def unregister(token: str) -> None: ...
def question_of(message_id: int) -> str | None: ...
def answer(question_id: str, text: str) -> bool: ...
def answer_tap(data: str) -> bool: ...
async def handle_callback(update, context) -> None: ...
async def ask(token: str, question: str, options: list[str] | None = None) -> str: ...
