from ..text import SESSION_ID_LABEL_LEN as SESSION_ID_LABEL_LEN, clip_chars as clip_chars, format_body as format_body, meta_bits as meta_bits, split_html as split_html, strip_tags as strip_tags, title_words as title_words

SEPARATOR: str
LEAD_CHARS: int
TITLE_WORDS: int
TITLE_CHARS: int

def quote(transcript: str) -> str: ...
def decorate(chunks: list[str], lead: str = '', total: int | None = None, start: int = 1) -> list[str]: ...
def room(limit: int, lead: str = '', pin: str | None = None) -> int: ...
def bare_frames(settled: str, unsettled: str = '', pin: str | None = None, footer: list[str] | None = None, limit: int = 4096, soft: int | None = None, lead: str = '') -> list[str]: ...
def frames(settled: str, unsettled: str = '', pin: str | None = None, footer: list[str] | None = None, limit: int = 4096, soft: int | None = None, lead: str = '', start: int = 1) -> list[str]: ...
def block(body: str, sid: str | None, title: str | None, provider: str | None = None, model: str | None = None, cost_usd: float | None = None, mode: str | None = None, context_used: int | None = None, context_window: int | None = None) -> str: ...
