from .. import reply as reply
from _typeshed import Incomplete

class Bubbles:
    origin: Incomplete
    anchors: Incomplete
    clock: Incomplete
    live: Incomplete
    all: Incomplete
    bare: dict[int, str]
    def __init__(self, working, origin, anchors, clock) -> None: ...
    async def write(self, bubble, text: str, markup=None, bare: str | None = None) -> bool: ...
    async def open(self, text: str, markup=None, bare: str | None = None): ...
    def cut(self) -> None: ...
    async def discard(self, bubble) -> None: ...
    def sealed(self) -> int: ...
