from . import answer as answer
from .. import reply as reply
from ..text import split_html as split_html

async def land(live, block: str, markup=None) -> list: ...
async def stamp(live, total: int) -> None: ...
