from ..chatkit import Bubble as Bubble, Origin as Origin
from ..streamkit import Clock as Clock

def test_text_written_after_a_question_lands_in_a_new_bubble() -> None: ...
def test_a_bubble_closed_by_a_question_is_never_written_again() -> None: ...
def test_the_status_line_leaves_the_bubble_a_question_closes() -> None: ...
def test_the_pin_moves_to_whatever_is_last() -> None: ...
def test_a_status_bubble_with_no_answer_in_it_is_removed() -> None: ...
def test_the_count_runs_across_the_whole_answer_not_per_segment() -> None: ...
def test_the_counter_closes_the_answer_and_the_footer_stays_last() -> None: ...
def test_the_answer_is_not_posted_a_second_time_below_the_questions() -> None: ...
def test_a_restamped_bubble_does_not_grow_a_second_counter() -> None: ...
def test_the_footer_never_gets_a_bubble_of_its_own() -> None: ...
