def test_the_tool_is_listed_with_the_question_it_needs() -> None: ...
def test_the_handshake_is_idempotent_because_the_cli_repeats_it() -> None: ...
def test_a_notification_is_answered_with_nothing_at_all() -> None: ...
def test_an_unknown_method_is_a_protocol_error_not_a_crash() -> None: ...
def test_the_cli_is_pointed_at_the_daemons_own_server_only_when_one_is_listening() -> None: ...
def test_the_prompt_stays_last_on_the_argv() -> None: ...
def test_plan_mode_does_not_offer_ask_because_the_cli_refuses_it() -> None: ...
def test_the_tool_can_be_taken_away_from_the_phone(store, monkeypatch): ...
def test_the_cli_tool_timeout_outlives_the_wait_the_bot_promises() -> None: ...
