from ..chatkit import Origin as Origin

def test_a_question_reaches_the_chat_and_its_answer_reaches_the_agent(): ...
def test_the_options_the_agent_offers_become_buttons(): ...
def test_a_tap_answers_with_the_option_it_carries(): ...
def test_a_free_text_reply_answers_the_question_it_replies_to(): ...
def test_an_unanswered_question_returns_text_not_an_mcp_error(monkeypatch) -> None: ...
def test_a_question_from_a_turn_that_ended_is_answered_in_text_too() -> None: ...
def test_the_turn_a_question_belongs_to_comes_from_the_url_not_the_payload() -> None: ...
def test_a_second_answer_to_the_same_question_is_ignored(): ...
def test_the_keyboard_dies_with_the_question(): ...
def test_ending_a_turn_releases_the_question_it_left_hanging(): ...
