from ..chatkit import Origin as Origin

def test_the_options_are_written_out_in_the_question_not_squeezed_into_buttons() -> None: ...
def test_the_buttons_are_the_numbers_of_that_list() -> None: ...
def test_a_tapped_option_answers_with_its_whole_text() -> None: ...
def test_the_answer_is_written_under_the_question_in_italic() -> None: ...
def test_an_unanswered_question_says_so_rather_than_quoting_the_agent() -> None: ...
def test_the_reply_hint_goes_once_the_question_has_an_answer() -> None: ...
def test_the_bubble_is_rewritten_from_what_was_SENT_not_from_telegrams_echo() -> None: ...
