def test_the_ask_url_becomes_each_clis_own_config() -> None: ...
def test_a_turn_that_may_not_ask_is_invoked_exactly_as_before() -> None: ...
def test_the_opencode_tool_call_outlives_the_wait_the_bot_promises() -> None: ...
def test_opencodes_own_overload_text_is_retried_like_a_529() -> None: ...
def test_an_overloaded_opencode_turn_reaches_the_retry_as_that_text() -> None: ...
