from _typeshed import Incomplete
from google.oauth2.credentials import Credentials

CONFIG_DIR: Incomplete
SCOPES: Incomplete

def auth(alias: str) -> Credentials: ...
def get_service(alias: str): ...
def fetch(alias: str, since_days: int = 7, max_results: int = 50) -> list: ...
def fetch_all(aliases: list, since_days: int = 7) -> list: ...
