import pathlib
from _typeshed import Incomplete

SLIDE_ID_PATTERN: Incomplete
URL_ID_PATTERN: Incomplete

def parse_slide_target(target: str) -> dict: ...
def download_public_export(presentation_id: str, out_path: pathlib.Path, format: str = 'pdf') -> pathlib.Path: ...
def extract_slide_texts(pdf_path: pathlib.Path) -> list[str]: ...
def clean_slide_lines(text: str, noise_tokens: set[str] | None = None) -> list[str]: ...
def cluster_and_sample(slides_text: list[str], max_samples: int = 25) -> list[dict]: ...
def render_sample_images(pdf_path: pathlib.Path, slide_numbers: list[int], out_dir: pathlib.Path, dpi: int = 150) -> dict[int, pathlib.Path]: ...
def sample_deck(target: str, out_dir: pathlib.Path | None = None, dpi: int = 150, max_samples: int = 25, keep_pdf: bool = True) -> dict: ...
