from _typeshed import Incomplete

SCOPES: Incomplete
SCOPES_WRITE: Incomplete
SLIDE_W: Incomplete
SLIDE_H: Incomplete

def get_service(alias: str, write: bool = False): ...
def get_presentation(alias: str, presentation_id: str, write: bool = False) -> dict: ...
def list_presentations(alias: str, name: str = '') -> list: ...
def create(alias: str, title: str) -> dict: ...
def apply(alias: str, presentation_id: str, requests: list) -> dict: ...
def url(presentation_id: str) -> str: ...
def textbox(object_id: str, page_id: str, text: str, x: float = 0.1, y: float = 0.1, w: float = 0.8, h: float = 0.15) -> list: ...
def move(object_id: str, x: float, y: float) -> dict: ...
def get_thumbnail_url(alias: str, presentation_id: str, page_object_id: str, size: str = 'LARGE') -> str: ...
