from _typeshed import Incomplete

SLIDE_W: Incomplete
SLIDE_H: Incomplete

def rotation_deg(transform: dict) -> float: ...
def eff_scale(transform: dict) -> tuple[float, float]: ...
def compose_transforms(pt: dict, ct: dict) -> dict: ...
def bounds(element: dict) -> tuple[float, float, float, float]: ...
