import pytest
from _typeshed import Incomplete

USAGE: Incomplete

def response(model: str, request: str | None, out: int = 500) -> dict: ...
@pytest.fixture
def project(tmp_path, monkeypatch): ...
def test_the_bug_itself_a_foreign_turn_stamped_opus_is_not_billed_as_opus(project) -> None: ...
def test_the_claimed_model_survives_in_the_label(project) -> None: ...
def test_a_real_anthropic_turn_is_still_priced(project) -> None: ...
def test_a_model_we_hold_no_rate_for_is_unpriced_even_with_a_request_id(project) -> None: ...
def test_no_rate_table_entry_prices_at_zero() -> None: ...
def test_the_roundup_line_says_unpriced_instead_of_naming_a_model(tmp_path) -> None: ...
