from pathlib import Path

def transcript(tmp_path: Path, records: list) -> Path: ...
def read_pair(uid: str, target: str, served: str, sidechain: bool = False) -> list: ...
def test_a_read_is_sized_by_what_it_served(tmp_path, monkeypatch) -> None: ...
def test_the_same_file_twice_is_a_re_read(tmp_path, monkeypatch) -> None: ...
def test_a_subagent_read_is_not_the_parent_sessions(tmp_path, monkeypatch) -> None: ...
def test_what_was_served_is_classified_by_the_gate_it_belongs_to() -> None: ...
