import pytest
from _typeshed import Incomplete

USAGE: Incomplete

def response(context: int, out: int, blocks: list, request: str = 'r1') -> dict: ...
def text(body: str) -> dict: ...
def thinking() -> dict: ...
@pytest.fixture
def project(tmp_path, monkeypatch): ...
def test_one_response_split_across_records_is_one_turn(project) -> None: ...
def test_the_records_of_one_response_pool_their_logged_output(project) -> None: ...
def test_thinking_is_billed_but_never_logged(project) -> None: ...
def test_tool_call_arguments_are_logged_output(project) -> None: ...
def test_the_same_request_id_in_two_sessions_stays_two_turns(project) -> None: ...
def test_a_response_with_no_request_id_is_still_a_turn(project) -> None: ...
def test_a_sidechain_response_never_enters_the_main_chain(project) -> None: ...
def test_a_thinking_heavy_session_does_not_read_as_self_authored(tmp_path) -> None: ...
