import pytest

def turn(context: int, content=None, request: str = 'r1') -> dict: ...
def result(tool_use_id: str, body: str, is_error=None) -> dict: ...
def use(tool_use_id: str, name: str, path: str = '') -> dict: ...
@pytest.fixture
def transcript(tmp_path): ...
def test_a_blocking_gate_is_counted_from_the_failed_tool_result(transcript) -> None: ...
def test_the_agent_quoting_the_gate_is_not_a_firing(transcript) -> None: ...
def test_only_context_md_reads_count_as_chain_reads(transcript) -> None: ...
def test_one_turn_split_across_records_is_counted_once(transcript) -> None: ...
def test_a_sidechain_turn_never_enters_the_main_chain(transcript) -> None: ...
def test_attribution_is_exact_in_aggregate(transcript) -> None: ...
def test_each_turn_calibrates_on_its_own_density(transcript) -> None: ...
def test_turn_one_is_the_session_start_payload_not_growth(transcript) -> None: ...
def test_a_session_with_nothing_to_calibrate_on_reports_no_ratio(transcript) -> None: ...
def test_a_hook_payload_stored_twice_is_counted_once(transcript) -> None: ...
def test_a_subagent_transcript_is_read_not_skipped(transcript) -> None: ...
def test_spend_is_measured_per_turn_from_the_shared_rate_model(transcript) -> None: ...
def test_a_source_is_counted_once_per_turn_it_appears_in(transcript) -> None: ...
