import pytest

STAMP: str

def response(cost_model: str = 'claude-opus-5', out: int = 500, request: str = 'r1', sidechain: bool = False) -> dict: ...
def spawn(tool_id: str, agent: str, kind: str = 'Explore', task: str = 'look') -> list: ...
def call(tool_id: str, name: str, sent: dict, back: str) -> list: ...
@pytest.fixture
def project(tmp_path, monkeypatch): ...
def test_a_worker_is_read_even_though_every_record_is_sidechain(project) -> None: ...
def test_the_spawn_names_the_type_and_the_worker_names_the_cost(project) -> None: ...
def test_a_worker_no_spawn_claimed_is_still_counted_and_named(project) -> None: ...
def test_a_worker_on_an_unbelievable_stamp_is_never_priced_at_opus(project) -> None: ...
def test_a_session_that_spawned_nothing_still_prices_its_main_thread(project) -> None: ...
def test_a_gap_wider_than_the_threshold_is_waiting_and_a_narrower_one_is_work(project) -> None: ...
def test_our_own_tool_is_ranked_under_its_own_name_not_under_bash(project) -> None: ...
def test_reading_a_tool_s_source_is_not_that_tool_printing(project) -> None: ...
def test_a_read_is_sized_by_what_came_back_not_by_what_was_asked(project) -> None: ...
