from _typeshed import Incomplete

HOOKS: Incomplete

def test_a_spec_named_the_legal_way_is_recorded_as_read() -> None: ...
def test_every_declared_spec_is_a_name_the_tracker_records() -> None: ...
def test_an_import_through_the_parent_facade_is_not_a_violation() -> None: ...
def test_an_import_descending_past_a_facade_still_is() -> None: ...
def test_the_checker_runs_clean_over_the_tree_it_first_refused() -> None: ...
