from _typeshed import Incomplete

HOME: str
NEEDLE: Incomplete

def test_only_one_versioned_file_spells_the_set() -> None: ...
def test_the_name_is_the_same_everywhere_it_is_read() -> None: ...
def test_every_reader_gets_the_definition_and_not_a_copy() -> None: ...
def test_a_facade_is_never_gated_on_its_own_stub() -> None: ...
