import pytest
from _typeshed import Incomplete
from collections.abc import Generator

GATE: str
MARKER: str
pytestmark: Incomplete

@pytest.fixture
def indexed_project() -> Generator[Incomplete]: ...
def test_the_nudge_fires_on_every_state_that_lets_the_read_through(indexed_project, state) -> None: ...
def test_the_nudge_names_the_project_root_not_the_file(indexed_project) -> None: ...
def test_it_is_said_once_per_project_per_session(indexed_project) -> None: ...
def test_a_blocked_read_does_not_spend_the_nudge(indexed_project) -> None: ...
def test_an_unindexed_project_is_silent(indexed_project) -> None: ...
