from _typeshed import Incomplete

HOOKS: Incomplete
POST_EDIT: Incomplete
UNKNOWN_TOOLS: Incomplete

def configs() -> list: ...
def registrations(event: str) -> list: ...
def test_both_harness_configs_are_readable() -> None: ...
def test_no_harness_filters_a_lifecycle_hook_by_tool_name(event) -> None: ...
def test_the_two_harnesses_run_the_same_hooks_after_a_tool_call() -> None: ...
def test_post_edit_leaves_a_non_write_payload_without_starting_an_interpreter(tool) -> None: ...
def test_post_edit_refuses_before_it_resolves_the_interpreter() -> None: ...
def test_post_edit_still_admits_a_write_from_a_tool_nobody_here_has_met(tool) -> None: ...
