import subprocess
from _typeshed import Incomplete

GATE: Incomplete
STORE: Incomplete
ELSEWHERE: Incomplete

def run(path, enabled: bool = True) -> subprocess.CompletedProcess: ...
def test_a_write_into_the_memory_store_is_refused() -> None: ...
def test_the_refusal_names_where_the_fact_goes_instead() -> None: ...
def test_a_write_anywhere_else_is_untouched() -> None: ...
def test_the_switch_really_switches_it_off() -> None: ...
