import subprocess
from _typeshed import Incomplete

DISPATCH: Incomplete
TABLE: Incomplete
HOOKS: Incomplete
WS: Incomplete

def rows() -> list[tuple[str, str, str, str]]: ...
def run(payload: dict, target=...) -> subprocess.CompletedProcess: ...
def call(tool: str, tool_input: dict, session: str) -> dict: ...
def with_table(table, session: str) -> subprocess.CompletedProcess: ...
def declare(table, *gates: tuple[str, str]) -> None: ...
def test_every_declared_gate_exists(path) -> None: ...
def test_every_declared_gate_has_a_known_moment_capability_and_class(moment, cap, path, kind) -> None: ...
def test_a_post_gate_does_not_run_at_pre() -> None: ...
def test_a_gate_guarded_by_dunder_main_actually_runs() -> None: ...
def test_a_block_keeps_its_own_words_and_its_own_exit_code() -> None: ...
def test_a_capability_that_selects_nothing_runs_nothing() -> None: ...
def informer(path, word: str): ...
def test_a_broken_gate_takes_only_itself(tmp_path) -> None: ...
def test_an_informing_gate_that_blocks_is_refused(tmp_path) -> None: ...
def test_two_informing_gates_produce_exactly_one_json_document(tmp_path) -> None: ...
