import pytest
from _typeshed import Incomplete

SHIM: Incomplete
STUB: str

@pytest.fixture
def rtk_path(tmp_path): ...
def test_a_command_stranded_after_cd_is_reached(rtk_path) -> None: ...
def test_every_line_is_rewritten_not_just_the_first(rtk_path) -> None: ...
def test_shell_it_cannot_read_is_left_exactly_as_written(command, rtk_path) -> None: ...
def test_a_single_line_is_rtk_s_own_business(rtk_path) -> None: ...
def test_a_payload_with_nothing_to_gain_stays_silent(rtk_path) -> None: ...
def test_a_non_bash_tool_is_not_touched(rtk_path) -> None: ...
def test_a_missing_rtk_fails_open() -> None: ...
def test_reaching_a_stranded_command_is_counted(rtk_path, tmp_path) -> None: ...
def test_a_payload_with_nothing_to_gain_is_counted_as_a_miss(rtk_path, tmp_path) -> None: ...
def test_a_missing_rtk_is_counted_as_such(tmp_path) -> None: ...
def test_counting_never_breaks_the_command_being_counted(rtk_path, tmp_path) -> None: ...
