GATE: str

def test_a_missing_stub_is_announced_and_the_read_is_allowed(tmp_path) -> None: ...
def test_the_announcement_is_made_once_per_file_per_session(tmp_path) -> None: ...
def test_an_empty_stub_counts_as_absent(tmp_path) -> None: ...
def test_a_type_with_no_interface_convention_stays_silent(tmp_path) -> None: ...
def test_a_present_stub_still_blocks(tmp_path) -> None: ...
def test_the_interface_map_answers_for_javascript(tmp_path) -> None: ...
def test_the_commit_sweep_reaches_a_stubless_javascript_sibling(tmp_path) -> None: ...
def test_the_counter_names_the_interface_the_source_actually_wants(tmp_path) -> None: ...
def test_a_facade_is_not_a_finding(tmp_path) -> None: ...
