from _typeshed import Incomplete
from pathlib import Path

URL_REGEX: Incomplete
FENCE_OPEN_REGEX: Incomplete
HEADING_REGEX: Incomplete
BULLET_REGEX: Incomplete
PATH_REGEX: Incomplete

def read_file(path: Path) -> str: ...
def extract_headings(text): ...
def extract_code_blocks(text): ...
def extract_urls(text): ...
def extract_paths(text): ...
def count_bullets(text): ...
def extract_inline_codes(text): ...
