from .extract import count_bullets as count_bullets, extract_code_blocks as extract_code_blocks, extract_headings as extract_headings, extract_inline_codes as extract_inline_codes, extract_paths as extract_paths, extract_urls as extract_urls, read_file as read_file
from _typeshed import Incomplete
from pathlib import Path

class ValidationResult:
    is_valid: bool
    errors: Incomplete
    warnings: Incomplete
    def __init__(self) -> None: ...
    def add_error(self, msg) -> None: ...
    def add_warning(self, msg) -> None: ...

def validate_headings(orig, comp, result) -> None: ...
def validate_code_blocks(orig, comp, result) -> None: ...
def validate_urls(orig, comp, result) -> None: ...
def validate_paths(orig, comp, result) -> None: ...
def validate_bullets(orig, comp, result) -> None: ...
def validate_inline_codes(orig, comp, result) -> None: ...

CHECKS: Incomplete

def validate(original_path: Path, compressed_path: Path) -> ValidationResult: ...
