from _typeshed import Incomplete

SCOPES: Incomplete
EVENT_FIELDS: str

def get_service(alias: str): ...
def list_calendars(alias: str) -> list: ...
def upcoming_events(alias: str, days: int = 7, cal_id: str = 'primary', max_results: int = 20) -> list: ...
def events_in_range(alias: str, date_from: str, date_to: str, cal_id: str = 'primary') -> list: ...
def fmt_events(events: list) -> list: ...
