LINE: str

def test_the_audio_filename_is_recovered_from_the_export_line() -> None: ...
def test_a_transcribed_audio_keeps_its_line_and_gains_the_words(tmp_path) -> None: ...
def test_an_audio_with_no_transcript_still_keeps_its_line(tmp_path) -> None: ...
def test_the_cartorio_bot_menu_is_dropped() -> None: ...
def test_the_header_reports_the_period_the_file_covers() -> None: ...
def test_a_punctuated_cpf_is_redacted_anywhere() -> None: ...
def test_a_bare_cpf_is_redacted_when_the_turn_before_asked_for_it() -> None: ...
def test_a_tracking_password_is_replaced_by_its_label() -> None: ...
def test_a_phone_number_is_not_mistaken_for_a_cpf() -> None: ...
