import subprocess
from _typeshed import Incomplete
from pathlib import Path

WOS: Incomplete
DASHBOARD: str

def git(repo, *args) -> subprocess.CompletedProcess: ...
def out(repo, *args) -> str: ...
def spawn(root, *command) -> subprocess.CompletedProcess: ...
def settle(repo, name: str, was_clean: bool, message: str, leave_dirty: bool) -> str: ...
def write_block(target: Path, name: str, body: str) -> None: ...
def verify_block(target: Path, label: str, verdict: str, log: str) -> None: ...
def regenerate(root: Path, leave_dirty: bool, clean: bool, promoting: str = '') -> tuple: ...
