from _typeshed import Incomplete
from pathlib import Path

MAP: str
HEAD: Incomplete

def declared(root: Path) -> set: ...
def link(url: str) -> str: ...
def home(folder: Path) -> str: ...
def known(text: str) -> dict: ...
def row_set_is_this_close_s_own_change(root: Path, rows: dict, seen: dict) -> bool: ...
def redraw(root: Path, leave_dirty: bool) -> str: ...
