from _typeshed import Incomplete

HERE: Incomplete
WORKSPACE_ROOT: Incomplete
HOOKS: Incomplete
TOOLS: Incomplete

def floor_of(**kw): ...
def git_lines(*args) -> list: ...
def needs(*paths: str) -> None: ...
def carries(path: str) -> bool: ...
def pytest_configure(config) -> None: ...
