from _typeshed import Incomplete

def paragraph(start: int, end: int, text: str, named_style: str = 'NORMAL_TEXT') -> dict: ...

DOC: Incomplete

def test_a_batch_that_edits_low_to_high_is_refused() -> None: ...
def test_the_same_batch_back_to_front_is_accepted() -> None: ...
def test_descending_turns_a_rejected_batch_into_an_accepted_one() -> None: ...
def test_a_style_only_batch_may_run_in_any_order() -> None: ...
def test_a_delete_shifts_indices_the_same_way_an_insert_does() -> None: ...
def test_the_refusal_names_the_fix_not_just_the_problem() -> None: ...
def test_an_index_read_out_of_the_outline_can_be_handed_straight_back_as_an_edit() -> None: ...
def test_the_outline_carries_the_revision_a_safe_write_needs() -> None: ...
def test_a_bullet_is_reported_as_a_bullet_not_as_normal_text() -> None: ...
def test_headings_keep_their_level() -> None: ...
def test_elements_without_text_stay_out_of_the_way_until_asked_for() -> None: ...
def test_a_revision_reaches_writecontrol_so_a_stale_batch_is_refused() -> None: ...
def test_no_revision_means_no_writecontrol_key_at_all() -> None: ...
def test_a_refusal_reaches_the_operator_as_a_message_not_a_traceback() -> None: ...
def test_comment_text_is_decoded_before_anyone_reads_it() -> None: ...
def test_replace_needs_no_index_and_so_needs_no_document_read() -> None: ...
