from _typeshed import Incomplete

NAO_SAO_FORMULARIOS: Incomplete
SPECS: Incomplete

def test_a_section_is_a_page_break_and_never_a_question() -> None: ...
def test_the_other_option_stays_an_other_and_does_not_become_a_choice() -> None: ...
def test_the_description_is_written_before_any_item_exists() -> None: ...
def test_items_land_in_the_order_they_were_written() -> None: ...
def test_a_scale_carries_its_bounds_and_its_labels() -> None: ...
def test_an_unknown_type_fails_here_rather_than_at_the_api() -> None: ...
def test_every_form_lucas_applies_still_compiles() -> None: ...
