def test_a_read_position_can_be_handed_straight_back_as_an_edit() -> None: ...
def test_size_accounts_for_scale_not_just_the_stored_magnitude() -> None: ...
def test_an_ordinary_api_text_box_is_not_mistaken_for_hidden() -> None: ...
def test_rotation_is_read_out_of_the_matrix_not_a_field() -> None: ...
def test_composing_with_an_identity_parent_changes_nothing() -> None: ...
def test_the_outline_carries_the_ids_an_edit_needs() -> None: ...
def test_elements_without_text_stay_out_of_the_way_until_asked_for() -> None: ...
def test_a_textbox_request_places_the_box_where_it_was_asked_to() -> None: ...
def test_get_thumbnail_url_calls_pages_get_thumbnail(monkeypatch): ...
