import pytest

@pytest.fixture
def mapfile(tmp_path): ...
def test_a_short_name_is_a_name_a_room_can_be_told(mapfile) -> None: ...
def test_a_short_name_stops_at_one_level_because_nobody_recites_a_tree() -> None: ...
def test_a_short_name_that_cannot_be_typed_from_memory_is_refused(bad) -> None: ...
def test_a_private_subtree_never_gets_a_public_short_name(short_name) -> None: ...
def test_the_file_recording_the_link_can_refuse_it_too() -> None: ...
def test_a_taken_short_name_is_refused_rather_than_moved(mapfile) -> None: ...
def test_a_target_that_is_not_a_url_never_reaches_the_site(mapfile) -> None: ...
def test_the_map_round_trips_through_the_file(mapfile) -> None: ...
def test_find_is_how_a_growing_map_stays_cheap(mapfile) -> None: ...
def test_the_redirect_file_is_what_cloudflare_reads(mapfile) -> None: ...
def test_the_redirect_is_302_because_a_301_outlives_the_fix(mapfile) -> None: ...
def test_check_reads_the_file_rather_than_trusting_the_writer(mapfile) -> None: ...
def test_the_real_map_is_clean() -> None: ...
