PAGE_ID: str
DASHED: str

def test_a_malformed_batch_sends_nothing_at_all() -> None: ...
def test_every_write_addresses_a_block_by_id_not_by_position() -> None: ...
def test_a_named_link_survives_the_trip_into_rich_text() -> None: ...
def test_a_run_over_notions_character_cap_is_cut_rather_than_refused() -> None: ...
