from _typeshed import Incomplete

TOOLS_ROOT: Incomplete
WORKSPACE_ROOT: Incomplete
PAGE_ID: str
DASHED: str

def block(kind: str, text: str, **extra) -> dict: ...
def test_a_pasted_page_url_reduces_to_the_id_the_api_wants() -> None: ...
def test_an_id_in_either_spelling_lands_on_the_same_uuid() -> None: ...
def test_text_carrying_no_id_is_refused_rather_than_guessed() -> None: ...
def test_the_outline_carries_the_block_ids_a_write_would_address() -> None: ...
def test_nested_blocks_indent_under_the_block_that_owns_them() -> None: ...
def test_a_finished_todo_reads_as_finished() -> None: ...
def test_an_unmapped_block_type_prints_what_it_is_instead_of_vanishing() -> None: ...
def test_a_database_row_shows_the_properties_that_carry_its_meaning() -> None: ...
def test_reading_a_page_does_not_drag_in_every_sub_page(monkeypatch): ...
def test_a_missing_token_names_the_one_command_that_stores_one(monkeypatch, tmp_path): ...
def test_the_recovery_text_names_a_tool_that_exists(monkeypatch, tmp_path): ...
def test_lucas_is_only_ever_asked_for_what_happens_inside_notion(monkeypatch, tmp_path): ...
def test_the_secret_is_never_stored_through_a_command_argument(monkeypatch, tmp_path): ...
def test_a_404_blames_the_connection_before_it_blames_the_id() -> None: ...
def test_the_stored_secret_is_not_readable_by_anyone_else(monkeypatch, tmp_path): ...
def test_the_cli_routes_its_entrypoint_through_run(tmp_path) -> None: ...
