import pytest
from _typeshed import Incomplete

ACCOUNTS: Incomplete

@pytest.fixture
def accounts(monkeypatch): ...
def test_secondary_alias_resolves_to_its_account_address(accounts) -> None: ...
def test_unknown_alias_says_where_to_look_rather_than_guessing(accounts) -> None: ...
def test_recovery_names_the_command_and_the_account(accounts) -> None: ...
def test_drive_write_recovers_with_the_write_flag(accounts) -> None: ...
def test_service_without_a_reauth_flag_still_gets_a_runnable_step(accounts) -> None: ...
def test_run_prints_the_instruction_instead_of_raising(accounts, capsys) -> None: ...

TOOLS_ROOT: Incomplete

def test_every_google_cli_routes_its_entrypoint_through_run(tmp_path) -> None: ...
def test_every_reauth_command_names_a_tool_that_exists() -> None: ...
