from _typeshed import Incomplete

compress: Incomplete

def test_a_compressed_file_keeps_its_final_newline(tmp_path) -> None: ...
def test_the_newline_is_restored_once_and_not_stacked(tmp_path) -> None: ...
def test_the_default_model_is_one_named_constant(tmp_path) -> None: ...
def test_caveman_model_overrides_the_default(monkeypatch) -> None: ...
