def scan(text: str) -> list[str]: ...
def test_every_declared_shape_is_found(kind, sample) -> None: ...
def test_the_near_misses_are_left_alone(innocent) -> None: ...
def test_a_bare_cpf_is_found_only_where_the_context_says_so() -> None: ...
def test_the_file_name_alone_is_a_finding(tmp_path) -> None: ...
def test_a_file_that_is_not_text_carries_no_finding(tmp_path) -> None: ...
def test_a_finding_never_quotes_the_value() -> None: ...
def test_the_enforcement_layer_is_clean_today() -> None: ...
