from _typeshed import Incomplete
from pathlib import Path

STUB_FOR: Incomplete
GATE_ON: Incomplete

def interface_for(path): ...
def stub_out_dir(path) -> Path: ...
def find_stubgen(): ...
def emit_pyi(path) -> bool: ...
def emit_dts(path, tsc) -> bool: ...
def find_tsc(): ...
def project_root(start: Path, stop: Path): ...
def emit_project_dts(project: Path, tsc: str) -> list: ...
def main() -> int: ...
