#!/usr/bin/env python3
# Generate the interface for ONE file: the single copy of every stub-generator invocation.
#
# Two paths need this and both are real triggers -- commit/generators.py stages the stub into the
# commit and sweeps stubless siblings, postedit/interfaces.sh keeps it current inside the session,
# which read/pre-read.py depends on because it blocks a source read only while the stub beside it is
# current. What must never be duplicated is the INVOCATION: there were two copies of the stubgen
# call and four near-identical tsc calls, drifting one flag at a time.
#
# Each function is silent and returns success; the caller owns what to print and whether to
# `git add`, because that is the one thing the two paths really do differently.
import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from platform_law import interpreter  # noqa: E402

# Which interface belongs beside a source. Lived as a private _STUB_FOR inside
# entropy/entropy_size.py, where only the COUNTER could reach it -- so the commit-time sweep meant
# to prevent that count could not ask the same question and answered a narrower one, in Python
# only. It sits here for the same reason the invocation does: one copy, and this file already
# dispatches on suffix in main().
#
# These four and no more on purpose. Widening it would make stub_signals report file types nothing
# has ever stubbed, inflating the count instead of draining it.
STUB_FOR = {'.py': '.pyi', '.ts': '.d.ts', '.tsx': '.d.ts', '.js': '.d.ts'}

# The wider set: which stub BLOCKS a read. `.dart` is generated by dart-api-extract, `.tex` by
# tex-interface-gen and `.csv` by hand, so the gate consults interfaces this file does not make --
# two honest questions with two honest answers. What was wrong is that they were two LANGUAGES: this
# half lived in a shell `case` inside the read gate, so no Python caller could ask it and the
# CONTEXT.md gate had no way to know a stub was about to block the same Read. Moving it here is what
# let that gate be ported at all -- both sets now sit together, their difference visible in one look.
GATE_ON = dict(STUB_FOR, **{'.dart': '.dart.api', '.tex': '.texif', '.csv': '.csvif',
                            '.tsv': '.tsvif'})


def interface_for(path):
    """The interface file that belongs beside `path`, or None if its type has no convention."""
    suffix = STUB_FOR.get(Path(path).suffix)
    return Path(path).with_name(Path(path).stem + suffix) if suffix else None


def stub_out_dir(path) -> Path:
    """Where a generated .pyi must be written.

    stubgen mirrors PACKAGE structure under -o, so for a file inside a package it writes
    `<out>/<pkg>/<name>.pyi`, not `<out>/<name>.pyi`. Passing the file's own directory as -o
    therefore produced a mirror of the path inside itself -- `scripts/scripts/*.pyi`,
    `engine/tests/unit/<subject>/unit/<subject>/*.pyi` -- one per package directory, all untracked,
    deleted by hand three times before the cause was named. The output root has to be the directory
    ABOVE the package root; only then does the mirror land where the source is. A non-package
    directory walks zero times and keeps the old behaviour.
    """
    directory = Path(path).resolve().parent
    while (directory / '__init__.py').is_file():
        directory = directory.parent
    return directory


def _run(command) -> bool:
    """A generator's own verdict, with its noise swallowed. Missing tool is False, never a raise."""
    try:
        return subprocess.run(command, capture_output=True, text=True,
                              encoding='utf-8', errors='replace').returncode == 0
    except (FileNotFoundError, OSError):
        return False


def find_stubgen():
    """The stubgen belonging to the interpreter that is running, falling back to PATH.

    NOT `-m mypy.stubgen`, which reads as the portable spelling and is not: mypy ships compiled on
    this machine (`mypy/__init__.cp312-win_amd64.pyd`), so the module has no code object and the
    call fails for every file while looking exactly like a stubgen that ran and found nothing.
    Derived from sys.executable rather than from a venv layout, so neither `bin` nor `Scripts` is
    named here -- platform_law.py owns that difference, and this only has to sit beside its Python.
    """
    from shutil import which
    beside = str(Path(interpreter()).parent)
    return which('stubgen', path=beside) or which('stubgen')


def _lf(path) -> None:
    """The stub, ending its lines the way this workspace declares rather than the way the tool did.

    stubgen and tsc write the file through their own runtime, so on a Windows clone every .pyi and
    .d.ts lands CRLF while .gitattributes declares LF for every clone. Git normalises on commit, so
    the REPOSITORY stays right and the WORKING TREE does not: each regenerated stub then shows as
    modified with an empty diff — unreadable in `git status`, and the state that refuses to start a
    merge (ISSUES.md B9). Measured 2026-09-01, five stubs deep, with the post-edit hook running
    normally.

    Here because neither generator takes a flag for it, and because this file is already the one
    copy of both invocations — a caller fixing its own output is where the two would drift apart.
    """
    target = interface_for(path)
    if not target or not target.is_file():
        return
    raw = target.read_bytes()
    if b'\r\n' in raw:
        target.write_bytes(raw.replace(b'\r\n', b'\n'))


def emit_pyi(path) -> bool:
    """mypy stubgen, into the output root above."""
    stubgen = os.environ.get('STUBGEN') or find_stubgen()
    if not stubgen:
        return False
    done = _run([stubgen, str(path), '-o', str(stub_out_dir(path)), '--quiet'])
    if done:
        _lf(path)
    return done


def emit_dts(path, tsc) -> bool:
    """TypeScript declarations BESIDE the source, one file at a time.

    Per file, never a tsc PROJECT build. That path was silently emitting nothing for years and
    needed two independent fixes to emit once: jsconfig.json implies noEmit:true (it is an editor
    aid), and "outDir": "." lands in tsc's default exclude list, so the config excluded its own
    directory. Forced past both it then hit TS5055 on every module with a sibling .d.ts -- our
    declarations sit beside their sources, so a project build reads its own previous output as an
    input. The per-file call has none of that and is idempotent.

    The .js arm differs by exactly two flags, which is why this is one function and not two: a
    second copy is how the four calls drifted apart in the first place.
    """
    path = Path(path)
    extra = (['--allowJs', '--checkJs', 'false'] if path.suffix == '.js' else ['--skipLibCheck'])
    done = _run([tsc, *extra, '--declaration', '--emitDeclarationOnly',
                 '--declarationDir', str(path.parent), '--target', 'ES2020', str(path)])
    if done:
        _lf(path)
    return done


def find_tsc():
    """The tsc this machine has, or None. `.cmd` on Windows, bare elsewhere -- asked of the
    filesystem through shutil, which already knows the difference, rather than of the OS."""
    from shutil import which
    return which('tsc') or which('tsc', path=str(Path.home() / '.local/bin'))


def project_root(start: Path, stop: Path):
    """The nearest ancestor of `start` holding a tsconfig.json, or None."""
    directory = (stop / start).parent
    while directory != stop and directory != directory.parent:
        if (directory / 'tsconfig.json').is_file():
            return directory
        directory = directory.parent
    return None


def emit_project_dts(project: Path, tsc: str) -> list:
    """Declarations for one tsconfig project at once, and the .d.ts files that came out.

    Per PROJECT, not per file: tsc --incremental costs one run for a directory tree and N runs for
    N files. The build-info marker is gitignored by this function rather than by the caller,
    because a caller that forgot would commit a binary cache — and it lives here for the reason
    the module head gives, that the tsc INVOCATION is the thing that must never be duplicated.
    """
    config = project / 'tsconfig.json'
    if (project / 'tsconfig.declarations.json').is_file():
        config = project / 'tsconfig.declarations.json'
    ignore, marker = project / '.gitignore', '.tsbuildinfo-declarations'
    if marker not in (ignore.read_text(encoding='utf-8') if ignore.is_file() else ''):
        with ignore.open('a', encoding='utf-8', newline='\n') as handle:
            handle.write(f'\n{marker}\n')
    subprocess.run([tsc, '-p', str(config), '--emitDeclarationOnly', '--incremental',
                    '--tsBuildInfoFile', str(project / marker)],
                   capture_output=True, text=True, encoding='utf-8', errors='replace')
    return [ignore] + [d for d in project.rglob('*.d.ts') if 'node_modules' not in d.parts]


def main() -> int:
    """`stubs.py <file>` -- emit the interface for one file. The entry point postedit uses."""
    if len(sys.argv) != 2:
        print('stubs.py: names one file', file=sys.stderr)
        return 2
    source = Path(sys.argv[1])
    if source.suffix == '.py':
        return 0 if emit_pyi(source) else 1
    tsc = os.environ.get('TSC') or find_tsc()
    if not tsc:
        return 127
    return 0 if emit_dts(source, tsc) else 1


if __name__ == '__main__':
    sys.exit(main())
