from pathlib import Path

def write_interface(tex_path: Path, data: dict, paper_root: Path | None) -> Path: ...
def check_relationships(data: dict, paper_root: Path) -> None: ...
def regenerate_labels(paper_root: Path) -> None: ...
def bib_check(bib_path: Path) -> None: ...
def main() -> int: ...
