from _typeshed import Incomplete
from pathlib import Path

EQ_ENVS: Incomplete
FLOAT_ENVS: Incomplete
LISTING_ENVS: Incomplete

def line_of(text: str, pos: int) -> int: ...
def extract_braced(text: str, open_pos: int) -> str: ...
def extract_caption(body: str) -> str | None: ...
def first_prose_snippet(text: str, after_pos: int, until_pos: int, n: int = 10) -> str | None: ...
def find_paper_root(path: Path) -> Path | None: ...
def word_count(text: str) -> int: ...
def parse_tex(path: Path) -> dict: ...
