from ..streamkit import FakeStream as FakeStream, deltas as deltas, result as result

def test_the_stream_yields_deltas_that_rebuild_the_exact_answer() -> None: ...
def test_deltas_concatenate_with_nothing_not_newlines() -> None: ...
def test_whole_segments_still_join_with_newlines() -> None: ...
def test_the_terminal_result_carries_session_cost_and_window() -> None: ...
def test_the_streamed_turn_satisfies_the_backend_contract() -> None: ...
def test_the_completed_assistant_message_is_not_double_counted() -> None: ...
def test_the_session_id_is_known_before_any_text_arrives() -> None: ...
def test_a_stream_without_deltas_degrades_to_the_result_text() -> None: ...
def test_a_stream_that_never_produced_a_result_is_an_error() -> None: ...
def test_thinking_and_tool_argument_deltas_are_never_painted() -> None: ...
def test_streaming_is_opt_in_on_both_backends() -> None: ...
def test_claude_only_asks_for_stream_json_when_streaming() -> None: ...
def test_the_fake_stream_really_yields_over_time() -> None: ...
