from ..chatkit import Bubble as Bubble, Origin as Origin
from ..streamkit import Clock as Clock

def test_split_html_is_prefix_stable_at_line_boundaries() -> None: ...
def test_a_growing_answer_is_sent_as_several_bubbles_while_it_streams() -> None: ...
def test_a_bubble_is_never_touched_once_a_later_one_exists() -> None: ...
def test_every_bubble_is_anchored_the_moment_it_is_born() -> None: ...
def test_only_the_live_bubble_carries_the_pin() -> None: ...
def test_no_bubble_ever_exceeds_the_telegram_limit() -> None: ...
def test_a_session_id_that_arrives_late_still_anchors_everything(): ...
def test_a_painter_with_nobody_listening_does_not_requeue_forever() -> None: ...
def test_sealing_can_be_turned_off_without_touching_the_streaming_knob() -> None: ...
def test_finish_lands_the_answer_without_duplicating_sealed_bubbles() -> None: ...
