from ..streamkit import Clock as Clock
from _typeshed import Incomplete
from frontend import reply as reply
from frontend.text import markdown as markdown
from frontend.text.htmlsplit import split_html as split_html

class _Chat:
    actions: Incomplete
    def __init__(self) -> None: ...
    async def send_action(self, action) -> None: ...

class _LiveMsg:
    edits: Incomplete
    fail: bool
    concurrent: int
    overlapped: bool
    chat: Incomplete
    message_id: int
    def __init__(self) -> None: ...
    async def edit_text(self, text, parse_mode=None, reply_markup=None) -> None: ...

def test_a_trickle_of_deltas_does_not_spend_a_round_trip_each() -> None: ...
def test_paints_are_spaced_by_the_throttle_interval() -> None: ...
def test_a_paint_in_flight_is_dropped_never_queued() -> None: ...
def test_a_failed_paint_widens_the_gap_and_a_good_one_narrows_it() -> None: ...
def test_the_interval_never_runs_away() -> None: ...
def test_the_pin_sits_at_the_end_of_the_live_bubble() -> None: ...
def test_the_finished_answer_carries_no_pin() -> None: ...
def test_typing_starts_on_the_very_first_delta() -> None: ...
def test_typing_is_relit_but_not_spammed() -> None: ...
def test_no_two_repaints_land_closer_than_the_configured_floor() -> None: ...
def test_the_pin_hangs_a_blank_line_below_the_answer_and_carries_no_glyph() -> None: ...
