from ..chatkit import Bubble as Bubble, Origin as Origin
from ..streamkit import Clock as Clock

def test_the_transcript_opens_every_bubble_not_a_bubble_of_its_own() -> None: ...
def test_the_quoted_transcript_is_escaped_and_clipped() -> None: ...
def test_a_single_bubble_answer_is_not_numbered() -> None: ...
def test_every_bubble_says_where_it_sits() -> None: ...
def test_a_bubble_born_mid_stream_counts_without_a_total() -> None: ...
def test_the_furniture_is_paid_for_before_the_split_not_after() -> None: ...
def test_a_streamed_voice_answer_keeps_the_quote_on_every_bubble() -> None: ...
def test_the_closing_pass_gives_every_bubble_its_exact_position() -> None: ...
def test_a_sealed_bubble_is_stamped_and_otherwise_left_alone() -> None: ...
def test_the_pin_sits_below_the_counter() -> None: ...
def test_a_row_holds_only_as_many_buttons_as_fit_uncut() -> None: ...
def test_a_long_option_stays_whole_in_the_message_and_in_the_answer(): ...
def test_the_status_line_never_opens_with_the_divider() -> None: ...
