from _typeshed import Incomplete

class _FakeSent:
    message_id: Incomplete
    def __init__(self, message_id) -> None: ...

class _FakeMsg:
    sent: Incomplete
    def __init__(self) -> None: ...
    async def reply_text(self, text, parse_mode=None, do_quote: bool = False, reply_markup=None): ...

def test_a_long_answer_is_split_even_though_it_fits_in_one_telegram_message() -> None: ...
def test_a_short_answer_is_still_a_single_bubble() -> None: ...
def test_no_chunk_is_empty_or_whitespace_only() -> None: ...
def test_a_chunk_ends_at_a_paragraph_break_not_mid_sentence() -> None: ...
def test_the_hard_limit_still_wins_over_the_soft_one() -> None: ...
def test_open_tags_survive_a_soft_split_too() -> None: ...
def test_nothing_is_dropped_across_the_split() -> None: ...
def test_deliver_returns_every_bubble_so_they_can_all_be_anchored() -> None: ...
def test_the_footer_rides_the_last_bubble() -> None: ...
def test_the_footer_title_runs_to_five_words() -> None: ...
def test_the_resume_picker_title_budget_is_unchanged() -> None: ...
