def test_only_text_that_can_no_longer_change_is_rendered() -> None: ...
def test_an_unclosed_code_fence_makes_every_later_break_unsafe() -> None: ...
def test_a_closed_fence_is_settled_again() -> None: ...
def test_a_frame_never_exceeds_telegram_even_with_the_pin() -> None: ...
def test_a_streamed_turn_still_ends_as_exactly_todays_answer() -> None: ...
