from ..chatkit import Bubble as Bubble, Origin as Origin
from ..streamkit import Clock as Clock

def test_bubbles_are_paced_apart_even_when_the_stream_outruns_them() -> None: ...
def test_only_one_bubble_is_born_per_paint() -> None: ...
def test_text_held_back_by_the_pause_is_not_lost() -> None: ...
def test_the_first_bubble_is_never_held_back() -> None: ...
def test_the_pause_is_never_silent() -> None: ...
def test_the_wait_is_shown_natively_and_never_as_a_bubble() -> None: ...
def test_the_indicator_outlives_a_whole_gap() -> None: ...
def test_a_slow_stream_is_not_slowed_further() -> None: ...
