def download_audio(url, runner=None): ...
def download_video(url, runner=None): ...
def transcribe(audio_path, model: str = 'base', lang=None, _model=None): ...
def ocr_image(img_path, lang: str = 'por+eng'): ...
def sample_frames(video_path, n: int = 5, workdir=None): ...
def ocr_frames(video_path, n: int = 5, lang: str = 'por+eng', workdir=None): ...
def caption_image(img_path, model_id: str = 'Qwen/Qwen3-VL-2B-Instruct', _vlm=None): ...
def caption_frames(video_path, n: int = 5, model_id: str = 'Qwen/Qwen3-VL-2B-Instruct', workdir=None): ...
