import pytest

@pytest.fixture
def store(monkeypatch): ...
def test_session_scope_and_new_scope_do_not_leak_into_each_other(store) -> None: ...
def test_harness_of_a_session_comes_from_its_lineage(store) -> None: ...
def test_harness_of_the_new_scope_is_a_knob(store) -> None: ...
def test_a_turn_leaves_its_knobs_as_the_defaults_a_new_session_inherits(store) -> None: ...
def test_writes_against_an_unknown_session_are_dropped(store) -> None: ...
def test_scope_resolves_from_the_message_the_keyboard_sits_on(store) -> None: ...
