import pytest

class _Fake:
    def __init__(self, items) -> None: ...
    def list_sessions(self, cwd): ...
    def session_detail(self, session_id, cwd): ...

@pytest.fixture
def two_backends(monkeypatch): ...
def test_recent_merges_and_sorts_newest_first(two_backends) -> None: ...
def test_recent_respects_limit(two_backends) -> None: ...
def test_recent_filters_by_title_query(two_backends) -> None: ...
def test_count_counts_filtered(two_backends) -> None: ...
def test_recent_adopts_shown_into_registry(two_backends) -> None: ...
def test_adopt_preserves_existing_mode(two_backends) -> None: ...
