from _typeshed import Incomplete

ROUNDUP_SKILL: Incomplete
HANDOFF_SKILL: Incomplete
TOOL: Incomplete

def test_the_skill_does_not_reinline_the_script() -> None: ...
def test_the_skill_calls_the_tool_by_path() -> None: ...
def test_a_skipped_handoff_deletes_the_artifact() -> None: ...
def test_the_handoff_may_decline_to_write_one() -> None: ...
def test_the_roundup_skill_does_not_promise_a_handoff_that_may_not_exist() -> None: ...
def test_the_template_has_no_placeholder_to_fill() -> None: ...
def test_the_state_block_is_whatever_the_tool_printed() -> None: ...
def test_what_the_session_cost_prints_before_the_state() -> None: ...
def test_the_inbox_phase_counts_instead_of_draining() -> None: ...
def test_the_template_caps_what_it_repeats() -> None: ...
def test_both_skills_agree_on_which_phase_promotes() -> None: ...
def test_the_dirty_flag_is_documented_where_it_is_decided() -> None: ...
