from _typeshed import Incomplete

CLOSE: Incomplete

def test_the_close_asks_whether_anything_drifted_before_it_writes() -> None: ...
def test_the_level_is_read_from_the_profile_and_never_chosen() -> None: ...
def test_a_missing_declaration_is_reported_and_not_guessed() -> None: ...
def test_the_cure_reaches_the_state_block() -> None: ...
def test_it_runs_before_the_suite_does() -> None: ...
