from _typeshed import Incomplete

SIZE: Incomplete
LAW: Incomplete

def test_a_session_that_only_deleted_reports_a_negative_net(tmp_path) -> None: ...
def test_a_vendored_or_generated_md_is_not_counted(tmp_path) -> None: ...
def test_without_a_session_it_reports_the_corpus_only(tmp_path) -> None: ...
def test_the_attribution_names_the_directory_that_moved_most(tmp_path) -> None: ...
def test_the_delta_obeys_the_same_scope_the_corpus_does(tmp_path) -> None: ...
def test_a_missing_transcript_is_not_a_failure(tmp_path) -> None: ...
