import pathlib
from _typeshed import Incomplete

WORKSPACE_ROOT: Incomplete
WORKSPACE_DIR: Incomplete

def config_dir() -> pathlib.Path: ...
def load_config() -> dict: ...
def save_config(**updates) -> dict: ...
def bot_token() -> str: ...
def allowed_chat_id() -> int: ...
