from .stream import answer as answer
from .text import split_html as split_html, strip_tags as strip_tags

TELEGRAM_MSG_LIMIT: int
SOFT_CHARS: int

async def safe_reply(msg, html_text: str, reply_markup=None) -> telegram.Message | None: ...
async def send_typing(message) -> None: ...
async def edit_text(message, html_text: str, reply_markup=None) -> bool: ...
async def send_voice(msg, ogg_bytes: bytes) -> telegram.Message | None: ...
async def drop(message) -> bool: ...
async def deliver(working_msg, msg, html_text: str, reply_markup=None, lead: str = '') -> list: ...
