from ..session import registry as registry
from _typeshed import Incomplete

LABELS: Incomplete
EFFORT_PREFERRED: Incomplete

def harness_values(scope: str) -> list[str]: ...
def model_values(scope: str) -> tuple[list[str], bool]: ...
def groups(scope: str) -> dict[str, list[str]]: ...
def effort_values(scope: str) -> list[str]: ...
def preferred(dim: str) -> tuple[str, ...]: ...
def values_for(scope: str, dim: str) -> tuple[list[str], bool]: ...
def warm() -> None: ...
def menu_dims(scope: str) -> list[str]: ...
