from telegram import InlineKeyboardButton

MAX_PER_ROW: int
NOOP: str

def per_row(labels: list[str]) -> int: ...
def cell(label: str, data: str | None) -> InlineKeyboardButton: ...
def segment(label: str, selected: bool) -> str: ...
def chunk(buttons: list[InlineKeyboardButton], per_row: int = ...) -> list[list]: ...
def framed(opener: InlineKeyboardButton, content: list[InlineKeyboardButton], closer: InlineKeyboardButton | None = None, tail: list[InlineKeyboardButton] | None = None) -> list[list]: ...
