from . import choices as choices, keyboard as keyboard, labels as labels
from ..session import registry as registry
from _typeshed import Incomplete
from telegram import InlineKeyboardButton, InlineKeyboardMarkup

SLOTS: Incomplete
PAGE: Incomplete

def root_markup(scope: str) -> InlineKeyboardMarkup: ...
def menu_markup(scope: str) -> InlineKeyboardMarkup: ...
def values_markup(dim: str, values: list[str], current: str | None, *, expanded: bool = False, page: int = 0, extra: list = ()) -> InlineKeyboardMarkup: ...
def all_button() -> InlineKeyboardButton: ...
def providers_markup(scope: str) -> InlineKeyboardMarkup: ...
def provider_markup(scope: str, name: str, page: int) -> InlineKeyboardMarkup: ...
