def test_bold_inside_a_table_cell_actually_renders() -> None: ...
def test_a_table_is_never_boxed_in_pre() -> None: ...
def test_code_and_links_in_cells_survive_too() -> None: ...
def test_three_column_rows_label_their_values_but_two_column_rows_do_not() -> None: ...
def test_an_already_bold_first_cell_is_not_double_wrapped() -> None: ...
def test_bold_wrapping_italic_does_not_cross_its_tags() -> None: ...
def test_triple_asterisks_nest_bold_and_italic() -> None: ...
def test_ordinary_bold_and_italic_are_untouched_by_the_fix() -> None: ...
