def test_a_name_that_fits_is_only_stripped_of_separators(monkeypatch) -> None: ...
def test_the_vendor_namespace_is_dropped(monkeypatch) -> None: ...
def test_every_separator_style_tokenizes_the_same(monkeypatch) -> None: ...
def test_the_version_dot_goes_too(monkeypatch) -> None: ...
def test_version_digits_survive_contraction(monkeypatch) -> None: ...
def test_contraction_keeps_names_apart_where_truncation_would_not(monkeypatch) -> None: ...
def test_inside_one_providers_page_the_prefix_is_dropped(monkeypatch) -> None: ...
def test_a_bare_alias_passes_through(monkeypatch) -> None: ...
def test_a_configured_alias_wins_over_the_rule(monkeypatch): ...
def test_every_provider_abbreviation_is_unique(monkeypatch) -> None: ...
