from .caps import Capabilities as Capabilities
from _typeshed import Incomplete
from dataclasses import dataclass
from typing import AsyncIterator, Protocol

EventKind: Incomplete
ASK_SERVER_NAME: str

@dataclass
class AgentEvent:
    kind: EventKind
    text: str = ...
    tool: str | None = ...
    session_id: str | None = ...
    cost_usd: float | None = ...
    model: str | None = ...
    context_used: int | None = ...
    context_window: int | None = ...
    partial: bool = ...

@dataclass
class TurnOptions:
    mode: str = ...
    title: str | None = ...
    model: str | None = ...
    effort: str | None = ...
    stream: bool = ...
    ask_url: str | None = ...

def add_flag(args: list[str], name: str, value: str | None) -> None: ...

class AgentBackend(Protocol):
    name: str
    def send(self, prompt: str, *, session_id: str | None, cwd: str, options: TurnOptions = ...) -> AsyncIterator[AgentEvent]: ...
    def list_sessions(self, cwd: str) -> list[dict]: ...
    def last_response(self, session_id: str, cwd: str) -> str: ...
    def session_detail(self, session_id: str, cwd: str) -> dict: ...
    def capabilities(self) -> Capabilities: ...
    def efforts(self, model: str | None = None) -> list[str]: ...
    def supports_ask(self, options: TurnOptions) -> bool: ...

def try_json(text: str) -> dict | None: ...

class LineParser(Protocol):
    def feed(self, line: str) -> list[AgentEvent]: ...
    def finish(self) -> list[AgentEvent]: ...

def check_contract(events: list[AgentEvent]) -> tuple[bool, str]: ...
