from .base import AgentEvent as AgentEvent, LineParser as LineParser, TurnOptions as TurnOptions
from .caps import Capabilities as Capabilities
from .proc import events_from_run as events_from_run, run_capture as run_capture, silent_run as silent_run, stream_lines as stream_lines
from typing import AsyncIterator

class CliBackend:
    name: str
    def build_args(self, prompt: str, session_id: str | None, options: TurnOptions) -> list[str]: ...
    def parse(self, stdout: str) -> list[AgentEvent]: ...
    def list_sessions(self, cwd: str) -> list[dict]: ...
    def last_response(self, session_id: str, cwd: str) -> str: ...
    def session_detail(self, session_id: str, cwd: str) -> dict: ...
    def stream_parser(self) -> LineParser | None: ...
    def occupancy(self, session_id: str, cwd: str) -> int | None: ...
    def model_used(self, session_id: str, cwd: str) -> str | None: ...
    def env(self, options: TurnOptions) -> dict | None: ...
    def supports_ask(self, options: TurnOptions) -> bool: ...
    def capabilities(self) -> Capabilities: ...
    def efforts(self, model: str | None = None) -> list[str]: ...
    async def send(self, prompt: str, *, session_id: str | None, cwd: str, options: TurnOptions = ...) -> AsyncIterator[AgentEvent]: ...
