from .base import AgentEvent as AgentEvent
from typing import AsyncIterator, Callable

async def run_capture(args: list[str], cwd: str, extra_env: dict | None = None) -> tuple[str, str, int]: ...
def child_env(extra_env: dict | None, cwd: str) -> dict: ...
async def stream_lines(args: list[str], cwd: str, extra_env: dict | None = None) -> AsyncIterator[tuple[str, str, int]]: ...
def silent_run(err: str, code: int) -> str: ...
def events_from_run(out: str, err: str, code: int, parse: Callable[[str], list[AgentEvent]]) -> list[AgentEvent]: ...
