from frontend.select import choices as choices, panel as panel

def test_no_row_exceeds_four_buttons(store) -> None: ...
def test_first_button_opens_or_goes_back_and_last_expands_or_collapses(store) -> None: ...
def test_back_walks_one_level_not_straight_to_the_root(store) -> None: ...
def test_paging_arrows_are_not_the_back_arrow(store) -> None: ...
def test_rows_split_evenly_rather_than_greedily(store) -> None: ...
def test_collapsed_picker_is_always_one_row(store) -> None: ...
def test_collapsed_picker_that_fits_shows_three_and_no_expander(store) -> None: ...
def test_the_selected_value_is_never_cut_off(store) -> None: ...
def test_a_value_chosen_in_the_drill_down_still_shows_in_the_shortlist(store) -> None: ...
def test_effort_shows_the_two_values_actually_used(store) -> None: ...
def test_the_expanded_effort_ladder_keeps_its_ordinal_order(store) -> None: ...
def test_expander_and_collapser_are_both_the_last_button(store) -> None: ...
def test_all_escape_rides_the_last_page_only(store) -> None: ...
def test_pager_is_its_own_row(store) -> None: ...
def test_arrows_park_at_the_ends_of_the_range(store) -> None: ...
def test_callback_data_never_spends_bytes_on_the_scope(store) -> None: ...
def test_provider_labels_drop_the_qualifier_nobody_reads(store) -> None: ...
