from _typeshed import Incomplete
from frontend.select import keyboard as keyboard

def test_effort_disappears_when_the_model_declares_none(store) -> None: ...
def test_root_is_the_dimension_row_because_mode_is_gone(store) -> None: ...
def test_session_menu_hides_harness_but_new_offers_it(store) -> None: ...
def test_new_scope_writes_defaults_not_a_session(store) -> None: ...
def test_choosing_a_harness_clears_the_model_it_cannot_mean(store) -> None: ...
def test_a_model_change_drops_an_effort_the_new_model_never_declared(store) -> None: ...
def test_an_effort_the_new_model_still_declares_survives(store) -> None: ...

class _Query:
    message: Incomplete
    drawn: Incomplete
    notes: Incomplete
    def __init__(self, message_id: int = 100) -> None: ...
    async def answer(self, text=None, show_alert: bool = False) -> None: ...
    async def edit_message_reply_markup(self, reply_markup=None) -> None: ...

def test_a_choice_redraws_where_it_was_made(store, monkeypatch) -> None: ...
def test_a_harness_change_steps_back_to_the_menu(store) -> None: ...
