from ..panelkit import Fake as Fake
from _typeshed import Incomplete

class _Query:
    message: Incomplete
    trace: Incomplete
    notes: Incomplete
    drawn: Incomplete
    def __init__(self, message_id: int = 100) -> None: ...
    async def answer(self, text=None, show_alert: bool = False) -> None: ...
    async def edit_message_reply_markup(self, reply_markup=None) -> None: ...

def test_a_tap_answers_and_redraws_concurrently_not_one_after_the_other(store) -> None: ...
def test_choosing_a_value_answers_exactly_once(store) -> None: ...
def test_the_choice_toast_survives_the_single_answer(store) -> None: ...
def test_every_navigation_tap_is_one_answer_and_one_redraw(store) -> None: ...
def test_a_mode_button_left_in_the_chat_redraws_instead_of_setting_a_mode(store) -> None: ...
def test_a_dimension_with_nothing_to_offer_alerts_without_redrawing(store) -> None: ...
def test_warm_asks_every_backend_for_its_declaration(monkeypatch): ...
