from frontend import phrases as phrases

def test_the_conditioning_prompt_is_prose_with_no_bare_word_list() -> None: ...
def test_the_prompt_ends_on_a_sentence() -> None: ...
def test_every_carrier_sentence_is_punctuated() -> None: ...
def test_the_models_lucas_says_out_loud_are_in_the_vocabulary() -> None: ...
def test_the_echo_is_italic_quotes_and_carries_no_label() -> None: ...
def test_a_misheard_bote_opener_is_normalized_before_it_is_echoed() -> None: ...
def test_normalize_leaves_a_message_that_never_opened_with_the_word_alone() -> None: ...
def test_a_selection_that_already_fits_does_not_reshuffle_the_row() -> None: ...
def test_a_selection_that_would_fall_off_the_row_is_still_hoisted() -> None: ...
def test_a_selection_missing_from_the_list_entirely_still_leads() -> None: ...
