from ..chatkit import FakeMsg as FakeMsg, FakeReplyAnchor as FakeReplyAnchor

def test_a_voice_note_is_acknowledged_before_the_transcription_runs(store, monkeypatch): ...
def test_the_status_bubble_becomes_the_turns_working_message(store, monkeypatch): ...
def test_an_overloaded_provider_is_retried_by_itself(store, monkeypatch) -> None: ...
def test_a_failure_about_the_request_itself_is_not_retried(store, monkeypatch) -> None: ...
def test_retrying_gives_up_and_says_so(store, monkeypatch) -> None: ...
def test_the_status_bubble_shows_the_transcript_before_the_answer_exists(store, monkeypatch): ...
