from _typeshed import Incomplete

class FakeSegment:
    text: Incomplete
    avg_logprob: Incomplete
    def __init__(self, text, avg_logprob=...) -> None: ...

class FakeModel:
    calls: Incomplete
    def __init__(self, segments) -> None: ...
    def transcribe(self, path, language: str = 'pt', initial_prompt=None, **kw): ...

def test_run_joins_segment_texts_and_primes_with_the_prompt() -> None: ...
def test_the_jargon_rides_in_initial_prompt_not_the_hotwords_arg() -> None: ...
def test_transcribe_lazily_loads_model_and_prompt(monkeypatch): ...
def test_transcribe_returns_empty_string_on_exception(monkeypatch): ...
def test_a_transcript_the_model_itself_doubts_is_rejected() -> None: ...
def test_a_confident_transcript_is_kept() -> None: ...
def test_confidence_is_the_mean_so_one_weak_segment_does_not_sink_a_turn() -> None: ...
def test_no_segments_at_all_is_not_confident() -> None: ...
