from _typeshed import Incomplete

class FakeMsg:
    sent: Incomplete
    def __init__(self) -> None: ...
    async def reply_voice(self, voice, **kw): ...

class FailingMsg:
    async def reply_voice(self, voice, **kw) -> None: ...

def test_send_voice_sends_the_ogg_bytes() -> None: ...
def test_send_voice_degrades_to_none_on_telegram_error() -> None: ...
