from _typeshed import Incomplete

class Bubble:
    chat: Incomplete
    text: Incomplete
    message_id: Incomplete
    edits: int
    markup: Incomplete
    deleted: bool
    def __init__(self, chat, text: str = '') -> None: ...
    async def edit_text(self, text, parse_mode=None, reply_markup=None) -> None: ...
    async def delete(self) -> None: ...
    async def edit_reply_markup(self, reply_markup=None) -> None: ...

class Chat:
    actions: Incomplete
    log: Incomplete
    def __init__(self) -> None: ...
    def next_id(self): ...
    async def send_action(self, action) -> None: ...

class FakeReplyAnchor:
    message_id: Incomplete
    def __init__(self, message_id) -> None: ...

class FakeMsg:
    reply_to_message: Incomplete
    def __init__(self, reply_to_message_id=None) -> None: ...

class Origin:
    chat: Incomplete
    sent: Incomplete
    def __init__(self) -> None: ...
    async def reply_text(self, text, parse_mode=None, do_quote: bool = False, reply_markup=None): ...
