from _typeshed import Incomplete

FAVS: Incomplete
CAPS: Incomplete

class Fake:
    def capabilities(self): ...
    def efforts(self, model=None): ...

def labels(markup): ...
def texts(markup): ...
def data(markup): ...
