from _typeshed import Incomplete
from backend.base import AgentEvent

def deltas(*texts: str, session_id: str = 's1') -> list[AgentEvent]: ...
def result(session_id: str = 's1', **kw) -> AgentEvent: ...

class FakeStream:
    events: Incomplete
    sent_with: dict | None
    def __init__(self, events: list[AgentEvent]) -> None: ...
    async def send(self, prompt: str, *, session_id=None, cwd: str = '', options=None): ...

class Clock:
    now: Incomplete
    def __init__(self, now: float = 1000.0) -> None: ...
    def __call__(self) -> float: ...
    def advance(self, seconds: float) -> None: ...
