from _typeshed import Incomplete

SCOPES: Incomplete
SCOPES_WRITE: Incomplete
LENGTH_CHANGING: Incomplete

class IndexOrderError(ValueError): ...

def get_service(alias: str, write: bool = False): ...
def get_document(alias: str, document_id: str, write: bool = False) -> dict: ...
def create(alias: str, title: str) -> dict: ...
def request_index(request: dict) -> int: ...
def check_order(requests: list) -> None: ...
def descending(requests: list) -> list: ...
def apply(alias: str, document_id: str, requests: list, revision_id: str = '', force: bool = False) -> dict: ...
def batch_body(requests: list, revision_id: str = '') -> dict: ...
def url(document_id: str) -> str: ...
def insert_text(index: int, text: str) -> list: ...
def replace_all_text(old: str, new: str, match_case: bool = True) -> list: ...
