from _typeshed import Incomplete

GDOC_MIME: Incomplete
MD_MIME: str
COMMENT_FIELDS: str

def list_documents(alias: str, name: str = '') -> list: ...
def export_md(alias: str, document_id: str) -> str: ...
def push_md(alias: str, document_id: str, md_path) -> dict: ...
def create_from_md(alias: str, title: str, md_path, folder_id: str = '') -> dict: ...
def comments(alias: str, document_id: str, include_resolved: bool = False) -> list: ...
