import datetime
import pathlib

CONFIG_FILENAME: str
CACHE_FILENAME: str
DEFAULT_TTL_SECONDS: int
MIME_GDOC: str
MIME_GSHEET: str
MIME_GSLIDE: str
MIME_GFORM: str

def load_config(dir_path: pathlib.Path) -> dict | None: ...
def save_config(dir_path: pathlib.Path, config: dict) -> None: ...
def load_cache(dir_path: pathlib.Path) -> dict: ...
def save_cache(dir_path: pathlib.Path, cache: dict) -> None: ...
def is_debounce_active(cache: dict, ttl_seconds: int = ..., now: datetime.datetime | None = None) -> bool: ...
def query_changed_files(alias: str, folder_id: str, since_iso: str | None = None) -> list: ...
def sync_file_item(alias: str, file_meta: dict, target_dir: pathlib.Path, generate_previews: bool = True) -> pathlib.Path | None: ...
def sync_directory(dir_path: pathlib.Path, account: str | None = None, force: bool = False, ttl_seconds: int = ...) -> dict: ...
