import pathlib
from _typeshed import Incomplete

SCOPES_READ: Incomplete
SCOPES_WRITE: Incomplete
EXPORT_MIME: Incomplete
EXPORT_MIME_OVERRIDES: Incomplete
EXPORT_EXT: Incomplete
FILE_FIELDS: str
GDOC_MIME: str

def get_service(alias: str, write: bool = False): ...
def list_files(alias: str, folder_id: str = 'root', page_size: int = 50) -> list: ...
def search_files(alias: str, query: str, page_size: int = 20) -> list: ...
def recent_files(alias: str, page_size: int = 30) -> list: ...
def download_file(alias: str, file_id: str, dest_dir: pathlib.Path, export_as: str = None) -> pathlib.Path: ...
def list_folder(svc, folder_id: str) -> list: ...
def find_or_create_folder(svc, name: str, parent_id: str, dry_run: bool = False) -> str: ...
def copy_file(svc, file_id: str, name: str, parent_id: str) -> dict: ...
def list_permissions(svc, file_id: str) -> list: ...
def grant_permission(svc, file_id: str, email: str = None, role: str = 'writer', kind: str = 'user', notify: bool = False) -> dict: ...
def trash_file(svc, file_id: str) -> dict: ...
def upload_local(svc, path: pathlib.Path, parent_id: str, as_gdoc: bool = False, name: str = None) -> dict: ...
