from _typeshed import Incomplete
from pathlib import Path

ROOT_VAR: Incomplete
PAYLOADS: Incomplete

def commands(config: Path, event: str) -> list: ...
def timed(command: str, payload: str, reps: int) -> float: ...
def floor(reps: int) -> None: ...
def main() -> int: ...
