from _typeshed import Incomplete
from pathlib import Path

HOOKS: Incomplete
DISPATCHERS: Incomplete
HOPS: int

def target(token: str, root: Path = ...) -> str: ...
def chain(entry: str = ..., root: Path = ...) -> list: ...
def code(text: str) -> str: ...
def index(root: Path = ...) -> tuple: ...
def reaches(seeds: list, root: Path = ...) -> dict: ...
