from _typeshed import Incomplete

SCOPES_READ: Incomplete
SCOPES_WRITE: Incomplete

def get_service(alias: str, write: bool = False): ...
def get_drive(alias: str): ...
def edit_url(form_id: str) -> str: ...
def create(alias: str, title: str, document_title: str = '') -> dict: ...
def get_form(alias: str, form_id: str) -> dict: ...
def apply(alias: str, form_id: str, requests: list) -> dict: ...
def list_responses(alias: str, form_id: str) -> list: ...
def move(alias: str, form_id: str, folder_id: str) -> dict: ...
def question_titles(form: dict) -> dict: ...
