from backend import TurnOptions
from dataclasses import dataclass

@dataclass
class TurnResult:
    text: str
    session_id: str
    cost_usd: float | None
    model: str | None = ...
    context_used: int | None = ...
    context_window: int | None = ...

class DispatchError(Exception): ...

def join_texts(events: list) -> str: ...
def events_to_result(events: list) -> TurnResult: ...
async def turn(prompt: str, *, session_id: str | None, backend_name: str, cwd: str, options: TurnOptions = ..., on_text=None) -> TurnResult: ...
