from . import directives as directives
from .. import phrases as phrases
from ..interview import ask as ask, askserver as askserver
from ..select import panel as panel
from ..session import registry as registry
from ..text import format as format
from backend import TurnOptions

def friendly_error(e: Exception) -> str: ...
def transient(e: Exception) -> bool: ...
def parse_new_arg(arg: str) -> tuple[str | None, str]: ...
def apply_directives(bot_prompt: str) -> str: ...
def turn_options(scope: str, title: str | None) -> TurnOptions: ...
def enable_ask(scope: str, backend_name: str, options: TurnOptions) -> str | None: ...
def persist_turn(session_id: str, backend_name: str, title: str | None, result, options: TurnOptions) -> None: ...
