from _typeshed import Incomplete
from pathlib import Path

LINK_RE: Incomplete
SCANNED: Incomplete
SKIP_DIRS: Incomplete

def staged_added_files() -> list: ...
def tracked_files(root: Path, nested: bool = False) -> list: ...
def tracked_paths(root: Path, nested: bool = False) -> set: ...
def owning_repo(path: Path, root: Path) -> Path: ...
def ignored_here(paths: list, root: Path) -> set: ...
def nested_repos(root: Path, depth: int = 3) -> list: ...
def declared_projects(root: Path) -> set: ...

MIRRORS: Incomplete

def is_generated_mirror(path: Path) -> bool: ...

ENFORCEMENT: Incomplete

def enforcement_paths(root: Path) -> set: ...

MEMORY_DIR: str

def wiki_exempt_paths(root: Path) -> set: ...
