from .. import config as config

MAX: int
NEW: str
DEFAULT_PANEL: str

def remember_reply(message_id: int, session_id: str) -> None: ...
def session_for_reply(message_id: int) -> str | None: ...
def remember_pending_new(message_id: int) -> None: ...
def pending_new(message_id: int) -> str | None: ...
def remember_ask(message_id: int, question_id: str) -> None: ...
def ask_question(message_id: int) -> str | None: ...
def remember_panel(message_id: int, state: str) -> None: ...
def panel_state(message_id: int, default: str = ...) -> str: ...
def scope_for_message(message_id: int) -> str | None: ...
