from . import msgmap as msgmap
from .. import config as config
from _typeshed import Incomplete

DEFAULT_BACKEND: str
DEFAULT_MODE: str

def remember(session_id: str, backend: str, title: str | None = None, preview: str | None = None) -> None: ...
def adopt(session_id: str, backend: str, title: str | None, updated_at: float) -> None: ...

NEW: Incomplete

def defaults() -> dict: ...
def setting_for(scope: str, key: str, default: str | None = None) -> str | None: ...
def set_setting(scope: str, key: str, value: str | None) -> None: ...
def harness_for(scope: str) -> str: ...
def remember_defaults(backend: str, mode: str, model: str | None, effort: str | None) -> None: ...
def backend_for(session_id: str) -> str | None: ...

STREAM_DEFAULT: bool

def streams(scope: str) -> bool: ...

ASK_DEFAULT: bool

def asks(scope: str) -> bool: ...
def mode_for(scope: str, default: str = ...) -> str: ...
def set_mode(scope: str, mode: str) -> None: ...
def title_for(session_id: str) -> str | None: ...
def remember_context_window(model: str | None, window: int | None) -> None: ...
def context_window_for(model: str | None) -> int | None: ...
