from . import registry as registry

def recent(n: int, query: str, cwd: str, offset: int = 0) -> list[dict]: ...
def count(query: str, cwd: str) -> int: ...
def last_response(session_id: str, cwd: str) -> str: ...
