import pathlib

SERVICE: str
INTEGRATIONS: str
CLI: str

class AuthMissing(RuntimeError): ...
class NotShared(RuntimeError): ...

def config_dir() -> pathlib.Path: ...
def token_path(alias: str) -> pathlib.Path: ...
def save_token(alias: str, token: str) -> pathlib.Path: ...
def load_token(alias: str) -> str: ...
def setup_text(alias: str) -> str: ...
def revoked_text(alias: str) -> str: ...
def not_shared_text(alias: str, target: str) -> str: ...
