from _typeshed import Incomplete

OPS: Incomplete

class OpRefused(ValueError): ...

def plan(operations: list) -> list: ...
def apply(alias: str, operations: list) -> list: ...
def load(path: str) -> list: ...
def text_op(alias: str, block_id: str, text: str) -> dict: ...
