from _typeshed import Incomplete

MARKERS: Incomplete

def rich_text(items: list) -> str: ...
def block_text(block: dict) -> str: ...
def marker(block: dict) -> str: ...
def prop_value(prop: dict) -> str: ...
def title_of(obj: dict) -> str: ...
def properties(obj: dict) -> str: ...
def outline(obj: dict, blocks: list, verbose: bool = False) -> str: ...
def row_line(row: dict) -> str: ...
