from _typeshed import Incomplete

API: str
VERSION: str
PAGE_SIZE: int
LEAF_TYPES: Incomplete

class ApiRefused(RuntimeError): ...

def normalize_id(raw: str) -> str: ...
def url(object_id: str) -> str: ...
def request(alias: str, method: str, path: str, body: dict | None = None) -> dict: ...
def paged(alias: str, method: str, path: str, body: dict | None = None, limit: int = 0) -> list: ...
def whoami(alias: str) -> dict: ...
def search(alias: str, query: str = '', kind: str = '', limit: int = 25) -> list: ...
def fetch(alias: str, ident: str) -> dict: ...
def blocks(alias: str, block_id: str, depth: int = 3) -> list: ...
def rows(alias: str, database_id: str, limit: int = 50) -> list: ...
def run(main_fn, *also) -> None: ...
