from _typeshed import Incomplete

def trend_label(counts): ...
def build_stats_block(name, attention): ...

DONE_RE: Incomplete

def compress_done(content, name): ...
def load_goal_files(): ...
def staged_goal_files(goal_files): ...
def pre_commit() -> None: ...
def check_compass_reminder() -> None: ...
def main() -> None: ...
