from _typeshed import Incomplete
from collections import defaultdict as defaultdict

MAX_DAYS: int

def parse_owns(path): ...
def governing_repo(rel_path): ...
def harvest(repo): ...

class Attention:
    missing: Incomplete
    def __init__(self, goal_files, owns_by_name=None) -> None: ...
    def count(self, name, days): ...
    def last_touch(self, name): ...
    def area_count(self, names, days): ...
