from .markdown import format_body as format_body

SESSION_ID_LABEL_LEN: int

def relative_time(ts: float, now: float | None = None) -> str: ...
def plain(text: str) -> str: ...

TITLE_CHARS: int
PREVIEW_CHARS: int

def clip_chars(text: str, limit: int) -> str: ...
def title_words(name: str | None, n: int = 3, limit: int = ...) -> str: ...
def title_from_prompt(prompt: str, n: int = 8) -> str: ...
def response_preview(text: str, n: int = 6) -> str: ...
def reattach_cmd(sid: str, backend: str | None = None) -> str | None: ...
def session_block(phrase: str, sid: str | None, title: str | None, body: str | None = None, extra: str | None = None, backend: str | None = None) -> str: ...
def short_model(model: str | None) -> str | None: ...
def context_pct(used: int | None, window: int | None) -> str | None: ...
def meta_bits(provider: str | None, model: str | None, mode: str | None, used: int | None = None, window: int | None = None) -> list[str]: ...
