import pathlib

def safe_name(filename: str) -> str: ...
def month_dir(base: pathlib.Path) -> pathlib.Path: ...
def unique_path(base: pathlib.Path) -> pathlib.Path: ...
def prune_old_attachments(base: pathlib.Path, max_days: int = 7) -> list[pathlib.Path]: ...
