from _typeshed import Incomplete

LIMITS: Incomplete

def test_both_levels_are_declared() -> None: ...
def test_the_column_cap_is_gone() -> None: ...
def test_the_implied_width_keeps_the_line_cap_in_front() -> None: ...
def test_no_tracked_file_is_blocked_today() -> None: ...
