from _typeshed import Incomplete

spec: Incomplete
type_gate: Incomplete
SCHEMA: Incomplete

def test_law_comes_from_schema() -> None: ...
def test_scopes_come_from_schema() -> None: ...
def test_allowlisted_name_passes(tmp_path) -> None: ...
def test_invented_type_is_blocked(tmp_path) -> None: ...
def test_lowercase_instance_is_never_checked(tmp_path) -> None: ...
def test_harness_mandated_name_is_exempt(tmp_path) -> None: ...
def test_prose_describing_finished_work_blocks_a_file_the_commit_adds(tmp_path) -> None: ...
def test_present_tense_state_is_not_a_corpse(tmp_path) -> None: ...
