from _typeshed import Incomplete

HOOKS: Incomplete

def test_an_extensionless_executable_is_code(tmp_path) -> None: ...
def test_an_extensionless_plain_file_is_not_code(tmp_path) -> None: ...
def test_shell_scripts_are_code(tmp_path) -> None: ...
def test_generated_stubs_are_not_code(tmp_path) -> None: ...
def test_prose_is_not_code(tmp_path) -> None: ...
def test_tex_is_code_because_papers_say_so() -> None: ...
def test_vendored_templates_are_exempt() -> None: ...
def test_every_checker_resolves_the_workspace_root_to_the_workspace() -> None: ...
def test_the_vendored_waiver_reaches_the_edit_gate() -> None: ...
def test_every_extensionless_tracked_file_is_explained() -> None: ...

NOT_THE_CODE_LAW: Incomplete

def test_no_checker_carries_its_own_extension_list() -> None: ...
def test_the_exemption_list_has_no_corpses() -> None: ...
def test_every_limit_has_one_home() -> None: ...
