from _typeshed import Incomplete

context_meter: Incomplete
transcript: Incomplete
LIMITS: Incomplete

def test_thresholds_come_from_limits_env() -> None: ...
def test_declared_in_limits_env() -> None: ...
def test_reads_the_most_recent_turn(tmp_path) -> None: ...
def test_subagent_turns_are_not_the_session(tmp_path) -> None: ...
def test_missing_or_unreadable_transcript_is_silent(tmp_path) -> None: ...
def test_each_threshold_announces_once(tmp_path, monkeypatch): ...
def test_the_loud_message_names_the_way_out(tmp_path) -> None: ...
def test_both_messages_name_roundup_and_nothing_else() -> None: ...
def test_the_warn_message_stays_ignorable() -> None: ...
def test_both_messages_stay_short_and_jargon_free() -> None: ...
def test_the_thresholds_bracket_the_measured_climb() -> None: ...
def test_the_handoff_artifact_is_not_an_uppercase_type() -> None: ...
def test_the_meter_never_spawns_a_session() -> None: ...
