from _typeshed import Incomplete

spec: Incomplete
entropy_citations: Incomplete

def test_no_item_number_is_cited_outside_a_roadmap() -> None: ...
def test_a_citation_in_source_is_a_hit(tmp_path) -> None: ...
def test_the_bare_form_is_a_hit(tmp_path) -> None: ...
def test_a_lettered_subitem_is_a_hit(tmp_path) -> None: ...
def test_a_roadmap_may_number_its_own_items(tmp_path) -> None: ...
def test_a_scoped_roadmap_may_too(tmp_path) -> None: ...
def test_a_lookalike_name_is_not_a_roadmap(tmp_path) -> None: ...
def test_the_retired_spelling_is_a_hit_even_in_a_roadmap(tmp_path) -> None: ...
def test_the_retired_word_alone_is_legal_portuguese(tmp_path) -> None: ...
def test_the_law_may_name_the_shape_it_forbids(tmp_path) -> None: ...
def test_a_front_without_a_number_is_prose(tmp_path) -> None: ...
def test_a_longer_token_is_not_a_hit(tmp_path) -> None: ...
def test_the_documents_stating_the_rule_may_quote_it() -> None: ...
def test_a_part_of_an_exempt_document_inherits_the_exemption() -> None: ...
def test_no_prose_restates_a_number_the_numeric_law_owns() -> None: ...
def test_a_stale_copy_of_the_line_law_is_a_hit(tmp_path) -> None: ...
def test_naming_the_owner_instead_of_the_number_passes(tmp_path) -> None: ...
def test_block_as_an_ordinary_word_beside_a_count_is_not_a_hit(tmp_path) -> None: ...
def test_a_generated_block_is_authored_by_nobody(tmp_path) -> None: ...
def test_the_checker_exempts_itself_and_its_tests() -> None: ...
