from _typeshed import Incomplete

spec: Incomplete
type_gate: Incomplete

def test_a_file_with_no_first_line_comment_owes_one(tmp_path) -> None: ...
def test_a_described_file_owes_nothing(tmp_path) -> None: ...
def test_a_shebang_is_not_a_description(tmp_path) -> None: ...
def test_a_file_the_routing_table_never_lists_is_not_asked(tmp_path) -> None: ...
def test_a_format_with_no_comment_syntax_is_sent_to_the_declaration_file(tmp_path) -> None: ...
def test_the_message_names_the_shape_the_file_needs(tmp_path) -> None: ...
def test_the_gate_runs_it_over_what_the_commit_adds(tmp_path) -> None: ...
