from _typeshed import Incomplete
from pathlib import Path

CITATION: Incomplete
NAMES: Incomplete
SECTION_END: Incomplete

def section_hits(files: list, root: Path) -> list: ...
def test_every_section_citation_names_a_section_that_exists() -> None: ...
def test_a_citation_of_a_section_that_moved_away_is_a_finding(tmp_path) -> None: ...
def test_a_bold_label_counts_as_a_section(tmp_path) -> None: ...
def test_a_pointer_inside_a_section_still_resolves(tmp_path) -> None: ...
def test_a_citation_wrapped_at_the_column_cap_is_read_whole(tmp_path) -> None: ...
def test_a_template_placeholder_is_not_a_pointer(tmp_path) -> None: ...
