from _typeshed import Incomplete
from pathlib import Path

ROOT: Incomplete

def is_skill(name: str) -> bool: ...
def is_command(name: str, src: Path) -> bool: ...
def disabled() -> set: ...
def list_skills(src: Path) -> list: ...
def list_commands(src: Path) -> list: ...
def sync_mirror(mirror: Path, src: Path, names: list) -> None: ...
def check_mirror(mirror: Path, src: Path, names: list) -> list: ...

PROTECTED_OR_LINK: Incomplete

def render_command(source: Path, src_dir: Path, dst_dir: Path) -> str: ...
def sync_commands(commands_dir: Path, src: Path, names: list) -> None: ...
def check_commands(commands_dir: Path, src: Path, names: list) -> list: ...
def orphans(prune: bool, mirrors: list, commands_dir: Path, src: Path) -> list: ...
