from _typeshed import Incomplete
from pathlib import Path

FLOW_TYPES: Incomplete
CONFIRMS: Incomplete
LEVELS: Incomplete

def frontmatter(path: Path) -> list | None: ...
def validate_skills(src: Path) -> list: ...
def validate_flows(workspace: Path) -> list: ...

DECLARES_LOOP: Incomplete
HAS_CAP: Incomplete

def validate_flow_loops(workspace: Path) -> list: ...
def validate_flow_dag(workspace: Path) -> list: ...
def validate_agents(workspace: Path) -> list: ...
