from _typeshed import Incomplete

FIX: Incomplete

class FakeProc:
    def __init__(self, stdout: str = '', stderr: str = '') -> None: ...

class FakeMedia:
    def __init__(self, spoken: str = '', screen: str = '', caption: str = '') -> None: ...
    def download_audio(self, url): ...
    def transcribe(self, path): ...
    def download_video(self, url): ...
    def ocr_frames(self, path): ...
    def caption_frames(self, path): ...

def test_metadata_parses_dump(): ...
def test_metadata_failure_no_crash(): ...
def test_clean_vtt() -> None: ...
def test_assemble_stops_at_metadata(): ...
def test_assemble_uses_captions(): ...
def test_assemble_speech_forced(): ...
def test_assemble_auto_escalates_to_speech_then_ocr(): ...
def test_assemble_auto_skips_heavy_when_metadata_suffices(): ...
def test_transcribe_joins_segments(): ...
def test_ocr_image_reads_fixture() -> None: ...
def test_source_of() -> None: ...
def test_save_no_overwrite(tmp_path): ...
def test_cli_usage_exits_1() -> None: ...

class ExplodingMedia(FakeMedia):
    def transcribe(self, path) -> None: ...

def test_image_post_never_reaches_transcribe(): ...
def test_no_audio_stream_does_not_reach_transcribe(): ...
def test_mixed_instagram_carousel_gathers_images(): ...
