from _typeshed import Incomplete

video_cli: Incomplete

def bundle(url, text: str = 'body', ok: bool = True, method: str = 'captions'): ...
def test_urls_from_text_reads_bare_markdown_and_parenthesised_links() -> None: ...
def test_urls_from_text_dedups_in_order() -> None: ...
def test_a_raising_extractor_does_not_abort_the_batch(): ...
def test_a_link_with_no_media_falls_back_to_web_fetch(): ...
def test_a_link_with_media_never_reaches_web_fetch(): ...
def test_from_file_reads_every_link_in_one_call(tmp_path) -> None: ...
def test_parse_args_keeps_the_single_url_form_and_its_flags() -> None: ...
def test_a_mixed_batch_prints_one_block_per_link_and_a_summary(capsys, monkeypatch): ...
def test_no_links_is_not_an_error(tmp_path, capsys) -> None: ...
