from _typeshed import Incomplete

TOOL: Incomplete

def test_every_declared_feature_reaches_the_matrix() -> None: ...
def test_an_unwired_feature_is_shown_rather_than_omitted() -> None: ...
def test_coverage_names_a_block_it_could_not_read(tmp_path) -> None: ...
def test_nothing_on_the_page_is_guessed_at(tmp_path) -> None: ...
def test_the_page_carries_everything_it_needs(tmp_path) -> None: ...
def test_the_output_is_deterministic(tmp_path) -> None: ...
def test_check_reports_stale_and_current(tmp_path) -> None: ...
def test_the_switch_is_honest(tmp_path) -> None: ...
def test_the_treemap_tiles_its_whole_area() -> None: ...
def test_the_spine_stops_at_its_depth_and_says_so() -> None: ...
