from _typeshed import Incomplete
from pathlib import Path

TEXT_FIELDS: Incomplete
PROJECTS: Incomplete

def project_name(root=None) -> str: ...
def label(att: dict) -> str: ...
def att_chars(att: dict) -> int: ...
def blocks(message: dict) -> list: ...
def output_chars(message: dict) -> int: ...
def walk(path: Path, sidechain: bool = False) -> dict: ...
def attribute(session: dict) -> tuple: ...
def median(values: list) -> float: ...
def spread(values: list) -> tuple: ...
