from _typeshed import Incomplete

IDLE_SECONDS: float
OURS: Incomplete
RUNNERS: Incomplete
SEGMENT: Incomplete
UNCLAIMED: str

def spawns(project: str, session: str = '') -> list: ...
def clock(project: str, session: str = '') -> dict: ...
def loudest(project: str, session: str = '') -> list: ...
def main_cost(project: str, session: str = '') -> tuple: ...
