from _typeshed import Incomplete
from pathlib import Path

def trusted_model(event: dict, model: str) -> str: ...

ROOT: Incomplete
CHARS_PER_TOKEN: float

def paths_for(project: str, session: str = '') -> list: ...
def responses(path: Path, sidechain: bool = False) -> dict: ...
def turns(project: str, session: str = ''): ...
