from _typeshed import Incomplete

RATES: Incomplete
COMPONENTS: Incomplete
UNPRICED: str

def priced(model: str) -> bool: ...
def turn_components(model: str, usage: dict) -> dict: ...
def turn_cost(model: str, usage: dict) -> float: ...
