from _typeshed import Incomplete

GATE: Incomplete
WS: Incomplete

def run(command: str, tool: str = 'Bash', tool_input: dict | None = None) -> str: ...
def test_a_heredoc_that_writes_a_workspace_file_is_named(command) -> None: ...
def test_analysis_and_ordinary_shell_stay_silent(command) -> None: ...
def test_a_write_outside_the_workspace_is_not_this_gate_s_business() -> None: ...
def test_a_redirect_inside_the_heredoc_body_is_text_not_shell() -> None: ...
def test_the_message_names_one_action() -> None: ...
def test_a_call_that_runs_no_command_is_not_touched() -> None: ...
