from _typeshed import Incomplete

ID: str
SECTION: Incomplete

def test_a_id_id_is_a_valid_id(tmp_path) -> None: ...
def test_a_id_spec_satisfies_its_id_across_the_notation_boundary(tmp_path) -> None: ...
def test_a_numeric_spec_does_not_pay_a_ids_debt(tmp_path) -> None: ...
