SECTION: str
B1_SECTION: str

def test_deleting_an_open_bug_without_a_spec_blocks(tmp_path) -> None: ...
def test_deleting_with_a_spec_passes(tmp_path) -> None: ...
def test_a_b19_spec_does_not_pay_b1s_debt(tmp_path) -> None: ...
def test_a_fixed_flip_with_a_spec_passes(tmp_path) -> None: ...
