from _typeshed import Incomplete

OVER: Incomplete
UNDER: Incomplete

def test_a_file_staged_over_the_cap_warns_though_the_working_copy_is_short(tmp_path) -> None: ...
def test_a_staged_fix_is_not_warned_about_by_a_long_working_copy(tmp_path) -> None: ...
def test_a_bare_audit_still_reads_the_disk(tmp_path) -> None: ...
def test_the_pipeline_asks_for_the_staged_blob() -> None: ...
