TRACKED: str
INTERPRETER: str

def test_a_body_that_writes_a_tracked_file_is_named() -> None: ...
def test_a_body_that_fails_either_condition_stays_silent(body) -> None: ...
def test_a_body_is_read_only_when_its_opener_fed_an_interpreter() -> None: ...
