from pathlib import Path
from workspace_meta import extract_api as extract_api

def test_an_all_empty_interface_column_is_dropped(tmp_path) -> None: ...
def test_a_column_with_one_real_value_survives(tmp_path) -> None: ...
def test_file_and_description_are_never_dropped(tmp_path) -> None: ...
def test_every_scanned_extension_has_a_way_to_be_described() -> None: ...
def test_a_shell_script_is_described_below_its_shebang(tmp_path) -> None: ...
def test_an_md_row_shows_its_blurb_not_its_heading(tmp_path) -> None: ...
def test_an_md_row_falls_back_to_its_heading(tmp_path) -> None: ...
def test_frontmatter_still_outranks_the_blurb(tmp_path) -> None: ...
def test_an_unanswered_scaffold_blurb_is_not_hoisted(tmp_path) -> None: ...
def test_a_multiline_module_docstring_describes_the_module(tmp_path) -> None: ...
def test_a_line_one_comment_outranks_the_docstring(tmp_path) -> None: ...
def test_a_folded_md_blurb_has_its_links_rebased(tmp_path) -> None: ...
def test_a_long_md_blurb_is_bounded(tmp_path) -> None: ...
def test_a_long_first_line_comment_is_bounded_too(tmp_path) -> None: ...
def test_a_short_first_line_comment_is_untouched(tmp_path) -> None: ...
def test_no_row_is_written_for_a_path_this_repo_is_told_to_ignore() -> None: ...
def test_a_nested_repo_and_a_generated_mirror_keep_their_rows(tmp_path: Path) -> None: ...
def test_preserved_descriptions_survive_a_narrower_table() -> None: ...
