def test_a_backslash_in_a_link_target_is_a_finding(tmp_path) -> None: ...
def test_the_generated_block_is_read_rather_than_stripped(tmp_path) -> None: ...
def test_a_posix_target_is_clean(tmp_path) -> None: ...
def test_the_whole_workspace_is_clean() -> None: ...
