from conftest import WORKSPACE_ROOT as WORKSPACE_ROOT

ALPHA: str
BETA: str

def test_the_open_count_is_derived_from_the_body(tmp_path) -> None: ...
def test_needs_lucas_is_counted_not_declared(tmp_path) -> None: ...
def test_a_sentence_about_the_marker_is_not_a_marked_item(tmp_path) -> None: ...
def test_an_item_id_survives_the_marker_in_front_of_it(tmp_path) -> None: ...
def test_declared_fields_come_from_the_header_lines(tmp_path) -> None: ...
def test_a_column_empty_on_every_part_is_not_emitted(tmp_path) -> None: ...
def test_the_marker_column_is_named_in_words(tmp_path) -> None: ...
def test_only_a_roadmap_part_is_counted_for_open_items(tmp_path) -> None: ...
def test_a_type_with_parts_and_no_index_is_left_alone(tmp_path) -> None: ...
def test_an_uncut_type_is_not_an_index(tmp_path) -> None: ...
def test_the_index_is_found_from_the_part_and_from_itself(tmp_path) -> None: ...
def test_a_lowercase_instance_never_looks_like_a_part(tmp_path) -> None: ...
