from _typeshed import Incomplete
from pathlib import Path

ROUTING: Incomplete

def test_relative_links_are_rebased_onto_the_child_directory() -> None: ...
def test_non_relative_targets_are_left_alone(target: str) -> None: ...
def test_truncation_never_cuts_a_link_in_half() -> None: ...
def test_truncation_never_cuts_a_word_in_half() -> None: ...
def test_a_cut_on_a_space_keeps_the_whole_last_word() -> None: ...
def test_text_within_the_limit_is_never_marked() -> None: ...
def test_hoisted_row_points_into_the_child(tmp_path: Path) -> None: ...
def test_delete_only_commit_still_runs_the_hook() -> None: ...
def test_routing_generator_consumes_the_deleted_list() -> None: ...
def test_subdir_rows_are_not_reported_as_removed_files(capsys, tmp_path: Path) -> None: ...
def test_stale_row_is_dropped_when_the_file_is_gone(tmp_path: Path) -> None: ...
def test_unsentineled_routing_section_is_replaced_not_appended(tmp_path: Path) -> None: ...
def test_facade_prefix_never_accumulates() -> None: ...
def test_repeated_sync_is_idempotent_for_a_commentless_facade(tmp_path: Path) -> None: ...
def test_no_tracked_context_has_a_doubled_facade_prefix() -> None: ...
def test_every_extensionless_tool_keeps_its_routing_row() -> None: ...
