def test_a_tracked_json_is_scanned() -> None: ...
def test_the_file_that_lost_its_row_can_describe_itself_again() -> None: ...
def test_every_declared_path_is_really_tracked() -> None: ...
def test_the_list_stays_narrow() -> None: ...
