from _typeshed import Incomplete
from pathlib import Path

CITATION: Incomplete
RETIRED_SPELLING: Incomplete
LIST_NAMES: Incomplete
LIMIT_CLAIM: Incomplete
GENERATED_BLOCK: Incomplete
LIMIT_OWNERS: Incomplete
ENFORCEMENT: Incomplete
WORKSPACE_ROOT: Incomplete

def citation_exempt_paths(root: Path) -> set: ...
def staged_files() -> list: ...
def citation_hits(files: list, exempt: set) -> list: ...
def limit_exempt_paths(root: Path) -> set: ...
def limit_hits(files: list, exempt: set) -> list: ...
def main() -> int: ...
