from _typeshed import Incomplete
from pathlib import Path

BUG_ID_RE: Incomplete
FIXED_RE: Incomplete
SKIP_DIRS: Incomplete

def bug_ids(text: str) -> set[str]: ...
def fixed_ids(text: str) -> set[str]: ...
def repo_root(path: Path) -> Path | None: ...
def has_spec(root: Path, bug_id: str) -> bool: ...
def main() -> int: ...
