from _typeshed import Incomplete

MAX_LINES: int
BLOCK_KEYWORD: Incomplete
CONTINUES: Incomplete

def ask_rtk(command: str) -> str | None: ...
def rewritten_command(out: str) -> str | None: ...
def rtk_rewrite(command: str) -> str | None: ...
def delegate(command: str) -> str: ...
def record(session_id: str, verdict: str, lines: int) -> None: ...
def splittable(lines: list[str]) -> bool: ...
def main() -> int: ...
