from pathlib import Path as Path

def test_the_redirect_clone_is_not_a_declared_project() -> None: ...
def test_every_project_that_keeps_a_list_is_one_git_declares() -> None: ...
def test_the_parse_rule_has_exactly_one_copy() -> None: ...
def test_the_list_stage_asks_before_it_writes() -> None: ...
def test_the_spec_sentence_and_the_code_still_agree() -> None: ...
def test_the_published_clone_carries_no_list() -> None: ...
