from _typeshed import Incomplete
from pathlib import Path

GOALS: Incomplete

def test_a_blank_line_ends_the_block(tmp_path: Path) -> None: ...
def test_a_following_blockquote_paragraph_is_not_owned(tmp_path: Path) -> None: ...
def test_a_wrapped_list_still_reads_as_one_block(tmp_path: Path) -> None: ...
def test_the_next_field_ends_the_block(tmp_path: Path) -> None: ...
def test_a_goal_with_no_block_owns_nothing(tmp_path: Path) -> None: ...
def test_no_live_goal_declares_a_sentence() -> None: ...
