from _typeshed import Incomplete

SCRIPT: Incomplete

def test_new_context_bearing_subdir_gets_allowlisted(tmp_path) -> None: ...
def test_context_free_subdir_is_left_ignored(tmp_path) -> None: ...
def test_exception_listed_subdir_is_never_added(tmp_path) -> None: ...
def test_already_allowed_subdir_is_untouched(tmp_path) -> None: ...
def test_running_twice_is_idempotent(tmp_path) -> None: ...
def test_healing_a_hidden_subdir_stops_the_commit(tmp_path) -> None: ...
def test_the_stopped_commit_had_nothing_staged_behind_the_callers_back(tmp_path) -> None: ...
def test_rerunning_after_the_user_stages_lets_the_commit_through(tmp_path) -> None: ...
def test_a_heal_that_hides_nothing_does_not_stop_the_commit(tmp_path) -> None: ...
def test_own_repo_subdir_is_never_touched(tmp_path) -> None: ...
