from _typeshed import Incomplete

BRAIN: Incomplete
DRAFTS: Incomplete

def tracked() -> set: ...
def declared_subtrees() -> list: ...
def test_brain_declares_subtrees_at_all() -> None: ...
def test_a_declared_brain_subtree_is_carried_by_git(subtree) -> None: ...
def test_the_drafts_that_started_this_are_the_ones_now_carried() -> None: ...
def test_a_model_named_in_a_filename_is_not_what_the_vendor_check_forbids() -> None: ...
