from _typeshed import Incomplete
from pathlib import Path as Path

PROJECTS: Incomplete
ROW: Incomplete

def declared_in_gitignore() -> set: ...
def listed_in_projects() -> set: ...
def test_every_declared_project_has_a_row() -> None: ...
def test_every_row_names_a_declared_project() -> None: ...
def test_the_table_reads_the_same_on_every_clone() -> None: ...
