from _typeshed import Incomplete
from pathlib import Path

MEMORY_DIR: Incomplete
EXCLUDE_DIRS: Incomplete
EXCLUDE_PREFIXES: Incomplete
STRUCTURAL_NAME: Incomplete
FENCE_RE: Incomplete
INLINE_CODE_RE: Incomplete
ROUTING_BLOCK_RE: Incomplete

def check_separators(root: Path, memory_dir: Path) -> list: ...
def check_pointers(root: Path, memory_dir: Path) -> list: ...
def test_pointer_integrity() -> None: ...
def test_dangling_relative_link_is_detected(tmp_path) -> None: ...
def test_clean_fixture_has_no_failures(tmp_path) -> None: ...
def test_no_committed_symlink_carries_an_absolute_path() -> None: ...
