def test_no_bash_tool_remains_under_core_tools() -> None: ...
def test_the_mirror_check_still_answers() -> None: ...
def test_the_check_spawns_nothing_while_it_runs() -> None: ...
def test_the_check_does_not_spawn_a_process_per_skill() -> None: ...
