def test_a_bash_target_runs_as_bash() -> None: ...
def test_a_python_target_still_reaches_the_interpreter() -> None: ...
def test_a_comment_containing_sh_does_not_make_a_python_tool_a_shell_script() -> None: ...
