from _typeshed import Incomplete

SETUP: Incomplete
PARTS: Incomplete
INSTALL_SKILL: Incomplete

def test_the_steps_region_exists() -> None: ...
def test_every_step_declares_its_feature() -> None: ...
def test_an_agent_runnable_step_has_all_three_parts() -> None: ...
def test_a_step_an_agent_cannot_finish_says_what_to_ask_for() -> None: ...
def test_every_step_can_be_checked() -> None: ...
def test_the_install_skill_is_a_door_not_a_copy() -> None: ...
def test_the_skill_sends_the_agent_to_the_file() -> None: ...
