def test_an_untracked_artifact_is_removed_rather_than_checked_out(tmp_path) -> None: ...
def test_an_untracked_artifact_is_committed_when_the_tree_is_ours(tmp_path) -> None: ...
def test_a_tracked_artifact_that_did_not_move_is_still_silent(tmp_path) -> None: ...
def test_a_tracked_artifact_is_still_restored_and_not_deleted(tmp_path) -> None: ...
