from _typeshed import Incomplete
from pathlib import Path

BASES: Incomplete

def repos(root: Path) -> list: ...
def unmerged_branches(root: Path, promoting: str = '') -> list: ...
def merged_local_branches(root: Path) -> list: ...
def unpushed_work(root: Path) -> list: ...
def merged_remote_branches(root: Path) -> list: ...
