def markers(name: str) -> tuple: ...
def line_pos(text: str, sentinel: str) -> int: ...
def replace_block(text: str, body: str, start: str, end: str, at_end: bool = False) -> str: ...
def main() -> int: ...
