from _typeshed import Incomplete
from pathlib import Path

DESC_LIMIT: int
SCAFFOLD_BLURB: str
LINK_RE: Incomplete
FIELD_RE: Incomplete

def md_blurb(path: Path) -> str: ...
def comment_paragraph(lines: list, start: int) -> str: ...
def rebase_links(text: str, prefix: str) -> str: ...
def truncate_outside_links(text: str, limit: int) -> str: ...
def hoist(text: str, prefix: str) -> str: ...
