from _typeshed import Incomplete
from pathlib import Path

ITEM: Incomplete
LUCAS_ITEM: Incomplete
NAME: Incomplete
EMPTY_CELL: Incomplete
ITEM_HEADLINE: Incomplete
PART_COLUMNS: Incomplete

def part_facts(path: Path) -> dict: ...
def render_table(headers: tuple, rows: list, always: tuple) -> str: ...
def parts_of(index: Path) -> list: ...
def index_for(path: Path) -> Path | None: ...
def item_headlines(path: Path) -> list: ...
def build_open_items(parts: list) -> str: ...
def build_part_rows(parts: list) -> str: ...
