from _typeshed import Incomplete
from part_table import EMPTY_CELL as EMPTY_CELL
from pathlib import Path

SPLIT_THRESHOLD: Incomplete

def is_scanned(path: Path) -> bool: ...
def carried(paths: list) -> list: ...
def code_files(directory: Path) -> list: ...
def has_code_content(directory: Path) -> bool: ...
def subdir_scan(directory: Path, rs: str, re_end: str) -> tuple: ...
def parse_preserved_files(inner: str) -> dict: ...
def parse_preserved_subs(inner: str) -> dict: ...
def build_sub_rows(link_list: list, preserved_subs: dict) -> str: ...

HEADERS: Incomplete
ALWAYS: Incomplete
FACADE_PREFIX: str

def build_file_rows(files_with_rel: list, preserved: dict, ctx_dir: Path) -> str: ...
def build_routing_block(sub_content: str, file_content: str, rs: str, re_end: str) -> str: ...
