from _typeshed import Incomplete
from file_law import CODE_EXTS
from pathlib import Path

CONTENT_EXTS: Incomplete
ALL_EXTS = CODE_EXTS | CONTENT_EXTS
PLACEHOLDER: str
COMMENT_RE: Incomplete

def file_description(path: Path) -> str: ...
def python_api(path: Path) -> list: ...
def js_api(path: Path) -> list: ...
def extract_api(path: Path) -> str: ...
def interface_for(src: Path, ctx_dir: Path) -> str: ...
