from _typeshed import Incomplete
from platform_law import interpreter as interpreter

CONTEXT_GATE: Incomplete
PRE_READ: Incomplete

def test_both_read_gates_name_the_same_complete_set() -> None: ...
def test_a_satisfied_read_costs_no_further_round_trip() -> None: ...
def test_a_stub_is_demanded_of_a_read_and_of_nothing_else() -> None: ...
def test_the_state_a_gate_acts_on_is_the_state_the_chain_reports(state, expected_rc, marker, tmp_path) -> None: ...
