from _typeshed import Incomplete

GATE: Incomplete
DEEP_PATH: str

def test_a_path_named_only_in_a_heredoc_body_does_not_gate() -> None: ...
def test_a_redirection_target_outside_the_body_still_gates() -> None: ...
def test_a_plain_command_still_gates() -> None: ...
def test_a_command_after_the_heredoc_is_still_read() -> None: ...
