from _typeshed import Incomplete

CONTEXT_GATE: Incomplete
BASH_GATE: Incomplete
DEEP_FILE: Incomplete

def test_the_main_thread_is_still_gated(gate, payload) -> None: ...
def test_a_subagent_is_exempt(gate, payload) -> None: ...
def test_agent_type_alone_does_not_exempt() -> None: ...
def test_the_spec_gate_is_not_exempted() -> None: ...
def test_the_rule_has_exactly_one_home() -> None: ...
