import pytest
from _typeshed import Incomplete
from collections.abc import Generator

HOOK: Incomplete

@pytest.fixture
def prompt_id() -> Generator[Incomplete]: ...
def test_a_path_in_the_prompt_becomes_a_briefing(prompt_id) -> None: ...
def test_the_briefing_carries_one_line_each_not_the_whole_head(prompt_id) -> None: ...
def test_a_path_ending_a_sentence_is_still_found(prompt_id, prose) -> None: ...
def test_a_prompt_naming_nothing_injects_nothing(prompt_id) -> None: ...
def test_workers_in_one_turn_share_the_turn_briefing(prompt_id) -> None: ...
def test_a_repeated_path_is_not_briefed_twice(prompt_id) -> None: ...
def test_an_unknown_turn_injects_nothing(prompt_id) -> None: ...
def test_the_hook_ignores_events_it_does_not_own(prompt_id) -> None: ...
