from _typeshed import Incomplete

TRACKER: Incomplete
FACADE_TRACKER: Incomplete
BATCH: int

def test_a_parallel_batch_of_context_reads_loses_no_mark() -> None: ...
def test_a_parallel_batch_of_interface_reads_loses_no_mark() -> None: ...
def test_a_parallel_batch_of_facade_reads_loses_no_mark() -> None: ...
def test_marking_the_same_path_twice_is_one_mark() -> None: ...
