from _typeshed import Incomplete

AGENTS: Incomplete
NORMS_DIR: Incomplete
FRONTMATTER: Incomplete

def test_every_norm_file_is_declared_and_every_declared_norm_exists() -> None: ...
def test_a_norm_declares_its_name_and_what_obeying_it_buys() -> None: ...
def test_the_always_loaded_block_matches_its_sources() -> None: ...
def test_a_norm_is_a_rule_and_not_an_essay() -> None: ...
def test_switching_a_norm_off_removes_it_from_the_prompt() -> None: ...
