from _typeshed import Incomplete

TOOL: Incomplete
REGISTRY: Incomplete
AGENTS: Incomplete

def test_every_kind_of_work_says_how_to_recognise_it_and_what_it_costs_to_go_lower() -> None: ...
def test_the_registry_never_names_a_model() -> None: ...
def test_the_adapter_fills_every_level_the_registry_declares() -> None: ...
def test_every_agent_declares_a_level_the_registry_defines() -> None: ...
def test_a_rendered_definition_points_at_the_role_instead_of_copying_it() -> None: ...
def test_check_notices_a_rendered_definition_that_drifted(tmp_path, monkeypatch): ...
def test_the_live_tree_matches_what_it_declares() -> None: ...
def test_the_map_is_not_sold_as_the_cost_answer() -> None: ...
def test_both_switches_exist_and_are_reachable(flag) -> None: ...
