from _typeshed import Incomplete

DECLARED: Incomplete

def test_every_third_party_import_is_declared() -> None: ...
def test_every_declared_row_is_complete() -> None: ...
def test_every_tool_runs_under_the_workspace_venv() -> None: ...
def test_the_check_runner_agrees_with_this_file() -> None: ...
