from _typeshed import Incomplete

SKILL_MIRROR: str
NORMS_GENERATOR: str
TOOL_LAW: str
GROUP_PUBLISHERS: Incomplete

def test_a_row_claiming_to_be_wired_really_is() -> None: ...
def test_an_unknown_name_fails_open() -> None: ...
def test_the_ablation_switch_turns_one_feature_off(monkeypatch) -> None: ...
def test_the_wired_gates_actually_consult_the_law(tmp_path) -> None: ...
def test_a_switched_off_tool_refuses_to_run() -> None: ...
