from _typeshed import Incomplete

SETUP: Incomplete
DEPS: Incomplete

def test_every_setup_step_maps_to_a_declared_feature() -> None: ...
def test_every_dependency_feature_is_a_declared_feature() -> None: ...
def test_a_skill_name_names_the_skill_file() -> None: ...
def test_every_row_is_complete_and_in_its_closed_set() -> None: ...
def test_runs_is_not_recoverable_from_enforcement() -> None: ...
def test_every_declared_feature_has_an_answer() -> None: ...
def test_the_cli_agrees_with_this_file() -> None: ...
