def test_a_deeper_root_wins_over_a_shallower_absent(monkeypatch) -> None: ...
def test_a_deeper_absent_still_wins_over_a_shallower_root(monkeypatch) -> None: ...
def test_the_real_floor_answers_both_the_same_way() -> None: ...
