from _typeshed import Incomplete

TOOL: Incomplete
REGISTRY: Incomplete
LEVELS: Incomplete

def test_every_level_declares_what_it_means_and_what_it_costs() -> None: ...
def test_the_levels_really_are_ordered_by_how_much_they_permit() -> None: ...
def test_only_the_open_level_stops_asking_about_secrets() -> None: ...
def test_a_harness_pattern_never_appears_in_the_registry() -> None: ...
def test_a_rendered_config_is_not_versioned() -> None: ...
def test_check_notices_a_config_that_no_longer_matches(tmp_path): ...
