def test_a_tree_grants_eligibility(monkeypatch): ...
def test_the_real_floor_ships_the_templates_the_craft_flow_points_at() -> None: ...
def test_every_escaping_kind_gets_a_gitignore_exception() -> None: ...
def test_the_target_regenerates_its_own_routing_rather_than_inheriting_ours() -> None: ...
def test_the_target_commits_under_the_branch_gate_like_every_other_repo() -> None: ...
def test_a_rebuilt_target_settles_in_one_pass() -> None: ...
