from pathlib import Path as Path

BOUNDED: str
UNBOUNDED: str
STATES_THE_RULE: str

def test_a_loop_with_a_numeric_cap_passes(tmp_path) -> None: ...
def test_a_loop_with_no_number_is_rejected(tmp_path) -> None: ...
def test_a_flow_declaring_no_loop_is_never_asked_for_a_cap(tmp_path) -> None: ...
def test_the_files_that_state_the_rule_are_not_judged_by_it(tmp_path) -> None: ...
def test_a_cut_flow_is_checked_against_its_whole_family(tmp_path) -> None: ...
def test_the_real_flow_corpus_is_clean() -> None: ...
