from _typeshed import Incomplete

HOOK: Incomplete

def test_the_failure_names_authentication_as_its_own_cause() -> None: ...
def test_the_three_causes_stay_three_branches() -> None: ...
def test_the_operator_is_shown_what_git_actually_said() -> None: ...
def test_the_hook_does_not_spawn_a_python_windows_does_not_have() -> None: ...
