def test_the_branch_this_close_is_promoting_is_not_a_finding(repo) -> None: ...
def test_naming_one_branch_does_not_excuse_another(repo) -> None: ...
def test_naming_no_branch_reports_every_one_of_them(repo) -> None: ...
def test_the_close_only_names_a_branch_it_will_actually_merge() -> None: ...
