import pytest
from _typeshed import Incomplete
from collections.abc import Generator
from pathlib import Path

MARKER: Incomplete

def marker_path(repo: Path) -> Path: ...
@pytest.fixture
def repo(tmp_path) -> Generator[Incomplete]: ...
def run(repo: Path, mode: str): ...
def test_a_session_that_stayed_on_its_branch_hears_nothing(repo) -> None: ...
def test_head_moving_under_the_session_is_named_with_its_recovery(repo) -> None: ...
def test_the_warning_fires_once_per_divergence_not_once_per_commit(repo) -> None: ...
def test_a_repo_with_no_marker_is_silent(repo) -> None: ...
def test_a_detached_head_is_a_rebase_not_a_drift(repo) -> None: ...
def test_outside_a_repo_it_says_nothing(tmp_path) -> None: ...
