import pytest
from _typeshed import Incomplete

HOOK: str
SOURCES: Incomplete
COMMANDS: Incomplete

def test_the_hook_is_silent_when_nothing_changed() -> None: ...
@pytest.mark.serial
def test_a_mirror_dirtied_by_a_merge_is_healed_in_one_line() -> None: ...
def test_the_hook_never_blocks() -> None: ...
def test_permissions_are_reported_and_never_written() -> None: ...
def test_a_command_link_is_rebased_with_posix_separators() -> None: ...
def test_the_switch_still_reaches_the_mirror() -> None: ...
