import pytest
from pathlib import Path

def git(repo: Path, *args): ...
def commit(repo: Path, name: str): ...
@pytest.fixture
def repo(tmp_path): ...
@pytest.fixture
def cloned(repo, tmp_path_factory): ...
