GATE: str

def test_a_field_naming_a_real_path_passes(tmp_path) -> None: ...
def test_a_field_naming_a_path_that_is_not_there_is_a_finding(tmp_path) -> None: ...
def test_every_item_in_the_list_is_checked(tmp_path) -> None: ...
def test_a_wrapped_field_is_one_field(tmp_path) -> None: ...
def test_the_description_is_not_glued_onto_the_first_field(tmp_path) -> None: ...
def test_a_sentinel_is_an_answer_not_a_path(tmp_path) -> None: ...
def test_a_path_in_governs_is_checked(tmp_path) -> None: ...
def test_prose_in_governs_is_left_alone(tmp_path) -> None: ...
def test_a_placeholder_names_a_shape_not_a_file(tmp_path) -> None: ...
def test_the_commit_gate_does_not_read_governs(tmp_path) -> None: ...
def test_a_field_that_must_be_a_path_and_is_a_word_is_a_finding(tmp_path) -> None: ...
def test_a_feature_field_names_the_registry(tmp_path) -> None: ...
def test_an_install_step_is_accepted_where_it_is_not_a_name(tmp_path) -> None: ...
def test_the_real_corpus_is_clean() -> None: ...
