def test_a_placeholder_is_not_finished_work(tmp_path) -> None: ...
def test_every_marker_variant_counts(tmp_path) -> None: ...
def test_only_context_files_carry_the_marker(tmp_path) -> None: ...
def test_a_generated_mirror_has_no_placeholder_to_answer(tmp_path) -> None: ...
def test_the_law_may_show_the_marker_it_defines() -> None: ...
