from _typeshed import Incomplete
from pathlib import Path as Path

LISTS: Incomplete

def test_retired_tokens_come_from_schema() -> None: ...
def test_a_longer_word_is_not_a_substring_hit(tmp_path) -> None: ...
def test_item_ids_read_item_position_only(tmp_path) -> None: ...
def test_sibling_namespaces_may_repeat_a_item_id(tmp_path) -> None: ...
def test_same_item_id_in_two_lists_is_a_duplicate(tmp_path) -> None: ...
def test_no_item_lives_in_two_lists() -> None: ...
def test_goal_vocabulary_holds_files_and_their_items(tmp_path) -> None: ...
def test_a_wiki_link_to_an_item_resolves(tmp_path) -> None: ...
def test_a_wiki_link_naming_nothing_is_flagged(tmp_path) -> None: ...
def test_every_wiki_link_in_the_workspace_resolves() -> None: ...
def test_memory_links_are_exempt_but_its_retired_tokens_are_not() -> None: ...
def test_strikethrough_is_a_corpse(tmp_path) -> None: ...
def test_a_dated_completion_report_is_a_corpse(tmp_path) -> None: ...
def test_a_date_without_a_completion_verb_is_not_a_corpse(tmp_path) -> None: ...
def test_a_tick_is_a_corpse_only_in_a_list(tmp_path) -> None: ...
def test_a_generated_mirror_is_not_reported(tmp_path) -> None: ...
def test_the_law_may_state_the_rules_it_enforces() -> None: ...
