from _typeshed import Incomplete
from pathlib import Path as Path

WARN: Incomplete
BASELINE: Incomplete

def test_no_new_directory_exceeds_the_crowding_signal() -> None: ...
def test_baseline_is_not_stale() -> None: ...
def test_a_small_directory_is_clean(tmp_path) -> None: ...
def test_an_over_full_directory_is_flagged(tmp_path) -> None: ...
def test_warn_and_block_are_reported_differently(tmp_path) -> None: ...
def test_a_flat_document_collection_is_not_crowding(tmp_path) -> None: ...
def test_interface_stubs_do_not_count_toward_crowding(tmp_path) -> None: ...
def test_the_threshold_has_exactly_one_home() -> None: ...
