COMPLETE: str

def test_a_complete_experiment_passes(tmp_path) -> None: ...
def test_a_missing_limitations_section_is_a_finding(tmp_path) -> None: ...
def test_what_changed_is_required_even_when_the_answer_is_nothing(tmp_path) -> None: ...
def test_the_question_line_must_be_line_two(tmp_path) -> None: ...
def test_the_directorys_own_two_documents_are_not_experiments(tmp_path) -> None: ...
def test_a_judged_reference_needs_a_level(tmp_path) -> None: ...
def test_a_tiered_reference_passes(tmp_path) -> None: ...
def test_the_unjudged_queue_is_exempt(tmp_path) -> None: ...
def test_a_prose_line_holding_a_link_is_not_a_reference(tmp_path) -> None: ...
def test_the_real_stores_are_clean() -> None: ...
