from _typeshed import Incomplete
from pathlib import Path as Path

BASELINE: Incomplete

def test_no_new_naming_violation() -> None: ...
def test_baseline_is_not_stale() -> None: ...
def test_spaces_and_accents_are_rejected(tmp_path) -> None: ...
def test_received_documents_keep_their_names(tmp_path) -> None: ...
def test_kebab_instance_and_snake_module_both_pass(tmp_path) -> None: ...
def test_type_name_shape_passes_only_for_a_known_type(tmp_path) -> None: ...
def test_mixed_name_dot_type_shape_is_rejected(tmp_path) -> None: ...
def test_uppercase_type_is_left_to_the_allowlist(tmp_path) -> None: ...
def test_uppercase_directory_is_flagged(tmp_path) -> None: ...
def test_scaffolding_directory_is_allowed(tmp_path) -> None: ...
def test_root_only_type_outside_root_is_flagged(tmp_path) -> None: ...
def test_readme_needs_a_repo_root(tmp_path) -> None: ...
def test_a_template_readme_is_not_a_claim(tmp_path) -> None: ...
