def test_no_list_assigns_a_model() -> None: ...
def test_a_bolded_model_assignment_is_a_finding(tmp_path) -> None: ...
def test_a_level_assignment_passes(tmp_path) -> None: ...
def test_a_model_name_as_DATA_passes(tmp_path) -> None: ...
def test_a_part_is_a_list_too(tmp_path) -> None: ...
def test_a_file_that_is_not_a_list_is_not_asked(tmp_path) -> None: ...
def test_an_exempt_path_may_name_the_shape_it_forbids(tmp_path) -> None: ...
