from ..chatkit import FakeMsg as FakeMsg

def test_route_text_bot_prefix_starts_new_session_with_spoken_flag(store, monkeypatch) -> None: ...
def test_route_text_reply_continue_threads_spoken_flag(store, monkeypatch) -> None: ...
def test_route_text_reply_continue_forwards_transcript_not_msg_text(store, monkeypatch) -> None: ...
def test_handle_reply_continue_dispatches_with_passed_text_not_msg_text(store, monkeypatch) -> None: ...
def test_empty_guard_true_for_blank_or_whitespace_transcript() -> None: ...
def test_empty_guard_false_for_real_transcript() -> None: ...
def test_transcribe_fail_phrases_is_a_nonempty_pt_bank() -> None: ...
def testrun_and_deliver_spoken_sends_voice_in_addition_to_text(store, monkeypatch): ...
def testrun_and_deliver_not_spoken_never_sends_voice(store, monkeypatch): ...
def test_bot_no_longer_owns_running_a_turn() -> None: ...
