def test_strip_bot_prefix_space() -> None: ...
def test_strip_bot_prefix_comma() -> None: ...
def test_strip_bot_prefix_case_insensitive() -> None: ...
def test_strip_bot_prefix_no_match() -> None: ...
