import pathlib
from google.oauth2.credentials import Credentials

def config_dir(service: str) -> pathlib.Path: ...
def get_accounts() -> list: ...
def primary_aliases() -> list: ...
def resolve_alias(alias: str) -> str: ...

class AuthExpired(RuntimeError): ...

def account_email(alias: str) -> str: ...
def recovery_text(alias: str, service: str, token_path: pathlib.Path) -> str: ...
def run(main_fn) -> None: ...
def auth(alias: str, service: str, scopes: list) -> Credentials: ...
