from _typeshed import Incomplete

RESPONSES: Incomplete
EXPORTS: Incomplete
FINE: Incomplete

def eol_rows() -> list: ...
def declared_lf() -> list: ...
def test_the_tree_declares_lf_for_something() -> None: ...
def test_no_declared_text_file_is_crlf_in_the_index() -> None: ...
def test_no_declared_text_file_is_crlf_in_this_working_tree() -> None: ...
def test_a_renormalised_export_still_parses_to_the_same_table(name, shape) -> None: ...
