import pytest
from _typeshed import Incomplete

SUITE: Incomplete
OFFENDERS: Incomplete

@pytest.fixture
def fake_root(tmp_path, monkeypatch): ...
def test_a_created_path_is_seen(fake_root) -> None: ...
def test_a_removed_path_is_seen(fake_root) -> None: ...
def test_a_tracked_file_whose_content_changed_is_seen(fake_root) -> None: ...
def test_an_untouched_tree_reads_identical(fake_root) -> None: ...
def test_the_guard_is_autouse_rather_than_something_a_test_opts_into() -> None: ...
def test_each_known_offender_declares_itself_serial(name, shape) -> None: ...
def test_the_suite_can_still_import_its_own_conftest() -> None: ...
