from _typeshed import Incomplete
from pathlib import Path as Path

SETTINGS: Incomplete

def test_the_capability_is_read_from_the_payload(tool, tool_input, expected) -> None: ...
def test_a_second_shell_is_gated_like_the_first() -> None: ...
def test_a_read_shaped_call_does_not_reach_the_command_gate() -> None: ...
def test_no_access_gate_is_filtered_by_a_tool_name() -> None: ...
