from _typeshed import Incomplete

ROOT: Incomplete

def test_the_local_file_is_read_on_top_of_the_shared_one(monkeypatch, tmp_path) -> None: ...
def test_a_clone_with_no_local_file_still_gets_every_answer(monkeypatch, tmp_path) -> None: ...
def test_the_local_file_is_not_versioned() -> None: ...
def test_a_switch_is_written_where_this_machine_is_asked(tmp_path) -> None: ...
