def test_the_run_summary_no_longer_supplies_occupancy() -> None: ...
def test_occupancy_comes_from_the_last_request_not_the_sum(): ...
def test_a_backend_that_cannot_measure_leaves_the_number_alone() -> None: ...
def test_only_the_result_event_is_touched(): ...
def test_an_impossible_percentage_is_withheld_rather_than_shown() -> None: ...
def test_a_real_percentage_still_renders() -> None: ...
