def test_last_turn_reads_the_assistant_not_the_trailing_user_message(tmp_path, monkeypatch) -> None: ...
def test_last_turn_reports_occupancy_not_lifetime_spend(tmp_path, monkeypatch) -> None: ...
def test_last_turn_empty_without_an_assistant_message(tmp_path, monkeypatch) -> None: ...
def test_context_used_none_when_nothing_was_counted() -> None: ...
def test_model_of_joins_provider_and_id() -> None: ...
