def test_effort_values_come_from_the_model_entry(monkeypatch) -> None: ...
def test_second_slash_belongs_to_the_model_not_the_provider(monkeypatch) -> None: ...
def test_toggle_and_budget_shapes_declare_no_effort(monkeypatch) -> None: ...
def test_undeclared_model_degrades_to_empty(monkeypatch) -> None: ...
def test_null_effort_values_are_dropped(monkeypatch) -> None: ...
def test_groups_bucket_by_first_segment(monkeypatch) -> None: ...
def test_favourites_rank_by_how_much_each_model_was_used(monkeypatch): ...
def test_a_model_no_longer_configured_is_not_offered(monkeypatch): ...
def test_no_history_falls_back_to_the_cheap_levels(monkeypatch): ...
