def test_latest_ai_title_wins_over_earlier() -> None: ...
def test_latest_ai_title_empty_when_absent() -> None: ...
def test_last_response_text_takes_last_assistant_text_block() -> None: ...
def test_last_response_text_empty_when_no_assistant() -> None: ...
def test_last_model_reads_assistant_message_model() -> None: ...
def test_tail_lines_reads_bounded_tail(tmp_path) -> None: ...
