def test_the_stream_itself_names_no_model_anywhere() -> None: ...
def test_the_model_is_read_from_the_store_like_occupancy(monkeypatch) -> None: ...
def test_a_model_the_stream_did_report_wins(monkeypatch) -> None: ...
def test_a_backend_that_cannot_say_leaves_it_empty() -> None: ...
def test_the_store_reads_provider_and_model_as_one_catalogue_id(monkeypatch): ...
