from _typeshed import Incomplete

ENV: Incomplete

def test_the_repo_writes_its_own_list_and_stages_it(tmp_path) -> None: ...
def test_the_list_says_it_is_about_this_repo(tmp_path) -> None: ...
def test_writing_a_list_never_refuses_the_commit(tmp_path) -> None: ...
