from _typeshed import Incomplete

KEYS: Incomplete

def report(**found) -> str: ...
def test_every_check_is_counted_even_when_it_is_clean() -> None: ...
def test_a_clean_check_gets_no_section() -> None: ...
def test_a_check_with_findings_gets_its_heading_its_note_and_its_items() -> None: ...
def test_the_headline_counts_what_has_no_section() -> None: ...
