import pytest
from pathlib import Path

def git(repo: Path, *args): ...
def commit(repo: Path, files: dict, days_ago: int): ...
@pytest.fixture
def repo(tmp_path): ...
def test_no_matching_revision_is_no_baseline(repo) -> None: ...
def test_a_revision_outside_the_window_is_not_a_baseline(repo) -> None: ...
def test_the_oldest_revision_inside_the_window_is_the_baseline(repo) -> None: ...
def test_the_baseline_spans_the_rename_from_entropy_md_to_issues_md(repo) -> None: ...
def test_issues_md_wins_over_entropy_md_in_the_same_revision(repo) -> None: ...
def test_a_smaller_window_excludes_a_revision_the_default_keeps(repo) -> None: ...
def test_format_trend_prints_the_dated_baseline_and_the_day_delta() -> None: ...
def test_format_trend_marks_a_falling_count_without_a_plus_sign() -> None: ...
def test_format_trend_with_no_baseline_is_the_empty_string() -> None: ...
def test_the_trend_flows_into_the_rendered_header() -> None: ...
def test_no_trend_argument_leaves_the_bare_count_unwriteable_as_flat() -> None: ...
