from _typeshed import Incomplete
from pathlib import Path as Path

LIST: Incomplete
HEADER: Incomplete

def test_the_generated_block_names_no_nested_project() -> None: ...
def test_the_root_list_carries_no_collected_total() -> None: ...
def test_the_header_counts_what_this_repo_tracks() -> None: ...
def test_branch_debt_answers_for_one_repo() -> None: ...
